# Builds assets/sdaia-icons.js — an inline SVG sprite of the Lucide icons used across the Academy sites.
# Run from anywhere:  powershell -File assets/_build/make-icons.ps1
# Source: https://github.com/lucide-icons/lucide (ISC licence)
$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$names = @(
  'arrow-left','arrow-right','arrow-up','arrow-up-right','arrow-down','award','badge-check','book-open','brain-circuit',
  'briefcase','building-2','calendar-days','chart-column','chart-pie','check','check-check','circle','circle-check',
  'circle-check-big','circle-alert','clock','compass','cpu','database','download','external-link','file-spreadsheet',
  'file-text','file-down','filter','flag','flask-conical','folder-tree','folder','gauge','git-branch','globe',
  'graduation-cap','handshake','key-round','landmark','languages','layers','layout-grid','lightbulb','link','list-tree',
  'map-pin','menu','moon','package','pencil-ruler','presentation','quote','rocket','route','search','shield-check',
  'shuffle','signal','sparkles','sun','sunrise','target','trending-up','trophy','users','users-round','wrench','x','zap',
  'chevron-down','chevron-right','chevron-left','chevron-up','sliders-horizontal','star','info','medal','microscope',
  'code','newspaper','school','scroll-text','layout-list','table','list','hash','timer','network','bot','shield',
  'user-round','pin','printer','share-2','plus','minus','refresh-cw','terminal','server','activity','tag','bell',
  'milestone','goal','hexagon','blocks','box','library-big','book-open-check','notebook-pen','pencil','file-badge',
  'file-check','id-card','brain','circuit-board','binary','git-merge','flame','gem','ribbon','home','mail','phone',
  'eye','lock','cog','chart-line','chart-bar','badge','crown','layers-2','book-marked','bookmark','calendar','map',
  'navigation','workflow','triangle','diamond','boxes','factory','coins','user-check','user-plus','contact',
  'briefcase-business','code-xml','braces','hard-drive','wand-2','sparkle','monitor','laptop','cloud','earth','globe-2',
  'arrow-down-to-line','folder-open','files','file','link-2','copy','maximize-2','minimize-2','circle-x','bar-chart-3',
  'layers-3','check-circle-2','sun-medium','moon-star','square-check-big','square-check','message-square-quote',
  'university','heart','settings'
)
$out = New-Object System.Text.StringBuilder
$ok = @(); $fail = @()
foreach ($n in $names) {
  $url = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/$n.svg"
  try {
    $svg = (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 30).Content
    # keep inner content only
    $inner = [regex]::Match($svg, '(?s)<svg[^>]*>(.*)</svg>').Groups[1].Value
    $inner = ($inner -replace '\s+', ' ').Trim()
    $inner = $inner -replace '\s*/>', '/>' -replace '> <', '><'
    [void]$out.Append("<symbol id=`"i-$n`" viewBox=`"0 0 24 24`">$inner</symbol>")
    $ok += $n
  } catch {
    $fail += $n
  }
}
$sprite = "<svg xmlns=`"http://www.w3.org/2000/svg`" class=`"sd-sprite`" aria-hidden=`"true`" focusable=`"false`"><defs>$($out.ToString())</defs></svg>"
$js = @"
/* SDAIA Academy - shared icon sprite (Lucide, ISC licence). Generated by assets/_build/make-icons.ps1 - do not edit by hand.
   Icons: $($ok.Count). Use:  <svg class="i"><use href="#i-NAME"/></svg> */
window.SDAIA_ICONS = '$($sprite -replace "'", "\'")';
"@
[System.IO.File]::WriteAllText((Join-Path $root 'sdaia-icons.js'), $js, (New-Object System.Text.UTF8Encoding($false)))
"OK: $($ok.Count)  FAIL: $($fail.Count)"
if ($fail.Count) { "Missing: " + ($fail -join ', ') }
