# Generates a lightweight bilingual index.html listing in every folder under Catalog/TrainingMaterials
# (folders only get one if they don't already have an index.html of their own).
# Static hosts (GitHub Pages, nginx, IIS) don't list directories, so the portal's folder links need these.
# Re-run after adding or removing training materials:
#   powershell -ExecutionPolicy Bypass -File assets/_build/make-dir-index.ps1
$ErrorActionPreference = 'Stop'
$academy = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$rootDir = Join-Path $academy 'Catalog\TrainingMaterials'
$utf8 = New-Object System.Text.UTF8Encoding($false)

$typeBadge = @{ '.pdf'='PDF'; '.docx'='DOCX'; '.doc'='DOC'; '.xlsx'='XLSX'; '.pptx'='PPTX'; '.md'='MD'; '.txt'='TXT'; '.zip'='ZIP'; '.html'='HTML'; '.png'='PNG'; '.jpg'='JPG' }
function Esc([string]$s) { $s -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;' }
function UrlEnc([string]$s) { [Uri]::EscapeDataString($s) }

function DepthTo([string]$from, [string]$to) {
  $rel = (Resolve-Path $from).Path.Substring((Resolve-Path $to).Path.Length).TrimStart('\')
  if ($rel -eq '') { 0 } else { ($rel -split '\\').Count }
}

$dirs = @(Get-Item $rootDir) + @(Get-ChildItem $rootDir -Recurse -Directory)
$made = 0
foreach ($d in $dirs) {
  $target = Join-Path $d.FullName 'index.html'
  # never overwrite a real page (marker comment identifies generated ones)
  if ((Test-Path $target) -and -not ((Get-Content $target -TotalCount 3 -ErrorAction SilentlyContinue) -join ' ').Contains('sdaia-dir-index')) { continue }
  $depth = DepthTo $d.FullName $academy
  $up = ('../' * $depth)
  $isRoot = $d.FullName -eq (Resolve-Path $rootDir).Path
  $parent = if ($isRoot) { $up + 'index.html' } else { '../index.html' }
  $items = ''
  foreach ($sub in (Get-ChildItem $d.FullName -Directory | Sort-Object Name)) {
    $items += "<li><span class='b dir'>DIR</span><a href='$(UrlEnc $sub.Name)/index.html'>$(Esc $sub.Name)</a></li>`n"
  }
  foreach ($f in (Get-ChildItem $d.FullName -File | Sort-Object Name)) {
    if ($f.Name -eq 'index.html') { continue }
    $ext = $f.Extension.ToLower(); $badge = if ($typeBadge.ContainsKey($ext)) { $typeBadge[$ext] } else { ($ext.TrimStart('.').ToUpper()) }
    $size = if ($f.Length -gt 1MB) { '{0:N1} MB' -f ($f.Length / 1MB) } else { '{0:N0} KB' -f [math]::Max(1, $f.Length / 1KB) }
    $items += "<li><span class='b'>$badge</span><a href='$(UrlEnc $f.Name)'>$(Esc $f.Name)</a><span class='s'>$size</span></li>`n"
  }
  $name = Esc $d.Name
  $html = @"
<!DOCTYPE html><!-- sdaia-dir-index: generated by assets/_build/make-dir-index.ps1 — safe to regenerate -->
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$name — أكاديمية سدايا | SDAIA Academy</title>
<meta name="robots" content="noindex">
<link rel="icon" type="image/png" href="${up}assets/academy-logo.png">
<style>
:root{color-scheme:light}
body{margin:0;font-family:"IBM Plex Sans Arabic","Segoe UI",Tahoma,system-ui,sans-serif;background:#F4F7FB;color:#0F1F33;line-height:1.8}
.wrap{max-width:860px;margin:0 auto;padding:2.5rem 1.25rem 4rem}
.top{display:flex;align-items:center;gap:14px;margin-bottom:1.6rem;flex-wrap:wrap}
.top img{height:40px;width:auto;background:#fff;border-radius:10px;padding:5px 10px;border:1px solid #E1E8F0}
h1{font-size:1.35rem;margin:0;color:#0B2A4E}
.crumb{font-size:13.5px;margin-bottom:1.2rem}
.crumb a{color:#1459A8;text-decoration:none}
.crumb a:hover{text-decoration:underline}
ul{list-style:none;margin:0;padding:0;background:#fff;border:1px solid #E1E8F0;border-radius:16px;overflow:hidden}
li{display:flex;align-items:center;gap:12px;padding:.7rem 1.1rem;border-bottom:1px solid #EDF2F7;font-size:14.5px}
li:last-child{border-bottom:none}
li a{color:#0F1F33;text-decoration:none;font-weight:500;overflow-wrap:anywhere}
li a:hover{color:#1459A8;text-decoration:underline}
.b{flex:none;font-size:10px;font-weight:700;letter-spacing:.4px;border-radius:6px;padding:2px 0;min-width:46px;text-align:center;background:#E8F0FA;color:#1459A8;font-family:Consolas,monospace}
.b.dir{background:#EEEBF7;color:#5B4A93}
.s{margin-inline-start:auto;font-size:12px;color:#5B6E84;white-space:nowrap;font-variant-numeric:tabular-nums}
.empty{padding:1.2rem;color:#5B6E84;font-size:14px}
</style>
</head>
<body>
<div class="wrap">
  <div class="top"><a href="${up}index.html"><img src="${up}assets/academy-logo.png" alt="SDAIA Academy"></a><h1>$name</h1></div>
  <div class="crumb"><a href="${up}index.html">بوابة الأكاديمية | Academy Portal</a> · <a href="$parent">المجلد الأعلى | Parent folder</a></div>
  <ul>
$items
  </ul>
</div>
</body>
</html>
"@
  [IO.File]::WriteAllText($target, $html, $utf8)
  $made++
}
"Generated $made directory index pages under Catalog\TrainingMaterials"
