C=[('NoufHar','Nouf Alharthi','SDAIA-Capstone','2026-10-07','',''),
('vecxtor0-prog','Mohammed Alhijji','RAG-Vector-Search-Faiss','2026-10-06','SDAIA Program for Developing AI Solution','genai'),
('hayaaldossari','Haya Aldossari','SDAIA-Academy-Projects','2026-10-05','AI training assignments and projects (SDAIA Academy); bio: AI Engineer','ai'),
('AtheerJB','Atheer Alshahrani','Loan-Project-SDAIA','2026-10-07','Applied Machine Learning project — SDAIA Applied ML','ai'),
('c3bod','Abdulelah Alharbi','sdaia-storytelling-tayseer-capstone','2026-10-06','SDAIA Academy storytelling capstone (SDA-DSC-112, Tayseer)','ds'),
('Mohammed-Ayman-Albilaly','Mohammed Ayman Albilaly','tayseer-digital-adoption-capstone','2026-10-06','SDAIA Data Visualization & Storytelling capstone (SDA-DSC-112)','ds'),
('GhadahAlsubaie','Ghadah Alsubaie','Tamweel-Lite-Advanced-Machine-Learning-Methods-Ghada','2026-10-06','Advanced Machine Learning Methods (Tamweel project)','ai'),
('shatha-alsubaie','Shatha Alsubaie','shatha-alsubaie-advanced-machine-learning-methods-tamweel','2026-10-06','Advanced Machine Learning Methods (Tamweel project)','ai'),
('progHYA','Haya Albaqami','Haya-Albaqami-SDAIA-NLP','2026-09-29','SDAIA NLP project','ai'),
('farahalrebh','Farah Alrebh','SDAIA-Farah-Hospital-AI-Labs','2026-10-06','SDAIA AI course labs','ai'),
('asmaMahdiNABEH','Asma Mahdi Nabeh','HR_PROJECT_FOR_SDAIA','2026-10-07','HR project for SDAIA','other'),
('farisalshashaa','Faris Alshashaa','LLM-Project-SDAIA-Program-','2026-10-06','LLM project — SDAIA programme (Mishwar chatbot)','genai'),
('AzamAlzahrani','Azam Alzahrani','SDAIA_GenAI','2026-10-05','Generative AI course assignments','genai'),
('NoufAbuhaimed','Nouf Abuhaimed','agentic-news-agents','2026-10-07','Multi-agent LangGraph system','genai')]
