# handle: (en, ar, progkey, basis, primary_repo, ar_verified)
A={
'shaimaalh':('Shaimaa Alharbi','شيماء الحربي','l0fae','dn+repo','Shaima_Alharbi_AI_Fundamentals_Capstone',0),
'Ahmadghaz':('Ahmad Ghazi Alotaibi','أحمد غازي العتيبي','l0fae','repo+h','Ahmad-Ghazi-Alotaibi-Project',0),
'maramaltalhah':('Maram Altalhah','مرام الطلحة','l0fae','repo+h','Maram-Altalha',0),
'shoog-m':('Shoog Alputty','شوق البطي','l0fae','repo+h','Shoog-alputty--Ai',0),
'shuruq2':('Shuruq Alotaibi','شروق العتيبي','aie211','rd+repo','ShuruqAlotaibi-NLP-Bayan',0),
'AbdulmajeedAlmosained':('Abdulmajeed Mansour Bin Mosained','عبدالمجيد منصور بن مسيند','aie211','rd+repo','bayan-nlp-AbdulmajeedBinMosend',0),
'AIShouq':('Shouq Khalid Aldossari','شوق خالد الدوسري','aie211','rd+repo','ShouqAldossari_Bayan_Applied_NLP',0),
'khalid-alajmi':('Khalid Alajmi','خالد العجمي','aie211','repo+h','bayan-applied-nlp-khalid-alajmi',0),
'3Maali':('Maali Alkhaldi','معالي الخالدي','aie211','dn+rd','bayan-nlp-3Maali',0),
'Manal-qaysi':('Manal Qaysi','منال قيسي','aie211','rd+h','Bayan_App_NLP3',1),
'aishaam2':('Aisha AlMajed','عائشة الماجد','dsc112','rd+h','Tayseer-SDAIAAcademy',0),
'Teefm-77':('Taif Mubarak Alshammari','طيف مبارك الشمري','dsc112','dn+rd','tayseer-capstone',0),
'ghayda-star':('Ghaida Al-Otyan','غيداء العتيان','dsc112','dn+rd','Tayseer-dashboard',0),
'Samm-006':('Sama Sultan Alzahrani','سما سلطان الزهراني','dsc112','dn+rd','Tayseer',0),
'amroalamro88':('Amro Alamro','عمرو العمرو','dsc112','rd+h','tayseer-capstone',0),
'almotirinajla':('Najla Saad Almutairi','نجلاء سعد المطيري','dsc112','rd+h','tayseer',0),
'vabdull':('Abdullah Sultan Alotaibi','عبدالله سلطان العتيبي','dsc112','dn+rd','tayseer-dashboard',0),
'NSulaiman4':('Noura Alsaif','نورة السيف','l0fgp','repo+h','GenAI-NouraAlsaif',0),
'imnuera25-ar':('Muneera Alqahtani','منيرة القحطاني','l0fgp','repo+h','GenAI-MuneeraAlqahtani',0),
'saraahamd1444-spec':('Sarah Alamari','سارة العماري','l0fgp','repo+h','gni-sarahalamari',0),
'ahmax23':('Ahmad Alharthi','أحمد الحارثي','l0fgp','dn+repo','GenAI-Ahmad-Alharthi-',0),
'lama9531':('Lama Alqarani','لمى القرني','l0fgp','li+repo','GENAI_LAMA',0),
'MaryamBuqrain':('Maryam Bu Qurayn','مريم بوقرين','advml','dn+repo','MaryamBuQurayn_Capston_Project_Advanced_ML_Techniques',0),
'Ralshatiri':('Rahaf Alshatiri','رهف الشطيري','cv26','dn','construction-safety-detection',0),
'ihdil':('Hadeel S. Alshahrani','هديل الشهراني','ml','dn+li','SDAIAMLProjects',0),
'iHaneenHMD':('Haneen Hamed Almabadi','حنين حامد المعبدي','llm','dn+li','LLMs-SDAIA',0),
'Janaalgh':('Jana Alghamdi','جنى الغامدي','ml','dn','SDAIA-ML-bootcamp',0),
'devAfnan':('Afnan Alsahli','أفنان السهلي','ml','dn+li','SDAIA_ML_Bootcamp',0),
'Wajdals':('Wajd Alsulaiman','وجد السليمان','ml','dn+li','ML-bootcamp-SDAIA',0),
'Faisal-Alkhuraif':('Faisal Alkhuraif','فيصل الخريف','t5','dn+h','Amazon-Sales-Analysis',0),
'manal-sa':('Manal Alshahrani','منال الشهراني','llm','dn+li','llm-bootcamp-SDAIA',0),
'shomookhAlharbi1900':('Shomookh Alharbi','شموخ الحربي','java','dn+h','sdaia_java_days',0),
'WadhaBinAwn':('Wadha Bin Awn','وضحى بن عون','java','dn+h','SDAIA-JAVA-CORSE',0),
'Thew7007':('Abdulrhman S. Alshahrani','عبدالرحمن الشهراني','java','dn','JavaCourseSdaia',0),
'MajedAlghamdi56':('Majed Alghamdi','ماجد الغامدي','java','dn+h','SDAIA-JavaCourseCW',0),
'DhayHamad':('Dhay Alduaylij','ضي الدعيلج','java','dn','SDAIA-Course-HW',0),
'joudxlll':('Joud Alrumayh','جود الرميح','java','dn+li','Sdaia-Java-FinalProject',0),
'HaifaMohammed':('Haifa Altuijri','هيفاء التويجري','java','repo+h','sdaia-haifa-altuijri-final-project',0),
'Nawafdata':('Nawaf Alomeir','نواف العمير','t5','dn+li','BootCamp_SDAIA_exercise-Exam',0),
'AzizAlbeshri':('Abdulaziz Albeshri','عبدالعزيز البشري','bc24','dn+h','SdaiaBootcamp',0),
'maram-a22':('Maram Alshehri','مرام الشهري','t5','dn','SDAIA-T5-Bootcamp',0),
'Noufsaleh46':('Nouf Almutairi','نوف المطيري','bc24','dn','SDAIA-Bootcamp',0),
'Joud-77':('Joud Bawjeeh','جود باوجيه','t5','dn+li','SDAIA-T5',0),
'7atemAlawwad':('Hatem Alawwad','حاتم العواد','bc24','dn+h','SDAIA-BOOTCAMP',0),
'SultanAlanazie':('Sultan Alanazi','سلطان العنزي','bc24','dn+li','Sdaia-Bootcamp',0),
'KFMBB':('Khalid F. AlBakr','خالد البكر','t5','dn+li','T5_Weekly_Tasks',0),
'AlyaaBajaber':('Alyaa Bajaber','علياء باجابر','zeham','dn+li','Data-Science-and-AI-SDAIA',0),
}
