# slug: (en, ar, progkey, posted_ago, evidence_summary)
L={
'hajar-al-shahrani':('Hajar Alshahrani','هاجر الشهراني','prod','18h','منشور إتمام شهادة «رفع الإنتاجية وتحسين العمليات» من أكاديمية سدايا'),
'dareen-alshehri1':('Dareen Alshehri','دارين الشهري','aaase','19h','منشور ختام برنامج «هندسة أنظمة الذكاء الاصطناعي التوكيلي المتقدمة» مع أكاديمية سدايا (سبقه منشور انطلاق)'),
'raghad-abdulmalik-814113361':('Raghad Abdulmalik','رغد عبدالملك','aie113','1d','منشور اجتياز برنامج «Software Engineering Practices for AI Systems» وشهادة الإنجاز، مشروع «موجّه»'),
'abdulaziz-alabdulkareem-b01535377':('Abdulaziz Alabdulkareem','عبدالعزيز العبدالكريم','bags','1mo','منشور إتمام «بناء أنظمة الذكاء الاصطناعي التوكيلي» وشهادة من أكاديمية سدايا (المدرب محمد البلادي)'),
'sarah-alaswad-9880a036b':('Sarah Alaswad','سارة الأسود','vibe','3w','منشور ختام برنامج «البرمجة التوليدية | Vibe Coding» مع مشاريع الفريق (أكّد، ثمر)'),
'rashed-alzeer-ba2374372':('Rashed Alzeer','راشد الزير','mde','3w','منشور الحصول على شهادة «هندسة البيانات الحديثة لأنظمة الذكاء الاصطناعي» — شهادته الثانية من أكاديمية سدايا'),
'rawanaldossari11':('Rawan Aldossari','روان الدوسري','creat','1mo','منشور إتمام «معسكر الإبداع بالذكاء الاصطناعي» (3 أيام) مع شكر أكاديمية سدايا'),
'shrouq-alzah':('Shrouq Alzahrani','شروق الزهراني','l0fgp','1w','منشور إتمام «Generative AI for Workplace Productivity» المقدَّم من أكاديمية سدايا'),
'nadin-alrabie-862296227':('Nadin Alrabie','نادين الربيعي','aaase','2d','منشور إنهاء «هندسة أنظمة الذكاء الاصطناعي التوكيلي المتقدمة» من أكاديمية سدايا'),
'layan-alhamad-3b8387230':('Layan Alhamad','ليان الحمد','aaase','3d','منشور استلام شهادة «Advanced Agentic AI Systems Engineering» بعد ثلاثة أيام في أكاديمية سدايا، مشروع «رفيق ميني»'),
'emad-alaskar-6308b73a9':('Emad Alaskar','عماد العسكر','mde','1w','منشور إتمام «Modern Data Engineering for AI Systems» مع أكاديمية سدايا (5 أيام)'),
'taleen-alammar-7b5b2a2a8':('Taleen Alammar','تالين العمار','cvu','5d','منشور إتمام «Computer Vision for Developers» من أكاديمية سدايا، مشروع «Privacy Guard»'),
'saudalajmi':('Saud Alajmi','سعود العجمي','ts','1w','منشور إتمام «تحليل السلاسل الزمنية والتنبؤ» — أولى دورات مسار علوم البيانات (دايكو × أكاديمية سدايا)'),
'anwar-saad-alotaibi-':('Anwar Saad Alotaibi','أنوار سعد العتيبي','ts','1w','منشور شهادة اجتياز «تحليل السلاسل الزمنية والتنبؤ» من أكاديمية سدايا، مشروع المسافرين الدوليين'),
'asayilalqahtani':('Asayil Alqahtani','أسائل القحطاني','vibe','18h','منشور ختام برنامج البرمجة السريعة/التوليدية (خمسة أيام، المدربة حنين المعيوف) مع مشروع الفريق'),
'ghzail-alotaibi-093162296':('Ghzail Alotaibi','غزيل العتيبي','vibe','1d','منشور إتمام «البرمجة التوليدية (Vibe Coding)» وشهادة الإتمام، مشروع «توّلى»'),
'leen-alhammad-9a8b6b338':('Leen Alhammad','لين الحماد','vibe','3w','منشور إتمام «البرمجة التوليدية»، مشروع «عائد»'),
'mohammed-hazazi-417596248':('Mohammed Hazazi','محمد حزازي','vibe','3w','منشور إتمام «البرمجة التوليدية (Vibe Coding)» بثلاثة مشاريع عملية'),
'layanalrouji':('Layan Alrouji','ليان الروجي','l0fae','5d','منشور إتمام «AI Fundamentals for the Workplace» في أكاديمية سدايا مع رابط مشروع البرنامج على GitHub'),
'sultan-alruwili-07671631b':('Sultan Alruwili','سلطان الرويلي','l0fae','2w','منشور إتمام «AI Fundamentals for the Workplace» مع أكاديمية سدايا'),
'raghad-alenezi---':('Raghad Alenezi','رغد العنزي','advml','2d','منشور إتمام «Advanced Machine Learning Methods» من أكاديمية سدايا'),
'shathaalslamah':('Shatha Alsalamah','شذى السلامة','creat','1mo','منشور إتمام «معسكر الإبداع بالذكاء الاصطناعي» المقدَّم من سدايا (المدرب ياسر فضايل)'),
'khaled-al-qahtani-997b2433a':('Khaled Al-Qahtani','خالد القحطاني','creat','1mo','منشور المشاركة في «معسكر الإبداع بالذكاء الاصطناعي» — سدايا'),
'meshal-albahouth-a94659416':('Meshal Albahouth','مشعل البحوث','creat','1mo','منشور إتمام «معسكر الإبداع بالذكاء الاصطناعي (AI Creativity Bootcamp)» المقدَّم من سدايا'),
'daniah-al-twaijri-1a1025261':('Daniah Al-Twaijri','دانية التويجري','dsc213','1w','منشور إتمام «Experimentation, A/B Testing, and Causal Inference» مع شهادة إتمام'),
'aalbujayr':('Anfal Al Bujayr','أنفال البجير','dsc213','1w','منشور حضور ورشتي «تصور البيانات وسرد القصص» و«التجارب واختبارات A/B والاستدلال السببي» ضمن البرامج التدريبية'),
}
