method: bayes
metric:
  name: val/accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 4
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.003
  weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.003
  augmentation_strength:
    values: [0.1, 0.2, 0.3, 0.4]
  batch_size:
    values: [32, 64]
