# Story-check verdicts, 3 Oct 2026 — logged-in LinkedIn /details/experience/ pages
# PASS = publish; HOLD = pending (reason); others = rejection codes written into d
PASS={
 531:dict(slug='hassanabid7',ar='حسن عبدالباسط عابد',en='Hassan Abid',year=2024,org='Devoteam',role='استشاري بيانات (Data Consultant)',
   program='ممارس النماذج اللغوية الكبيرة LLM Practitioner (نوفمبر 2023) + معسكر T5 لعلوم البيانات والذكاء الاصطناعي (يوليو–أكتوبر 2024) — أكاديمية سدايا',period='سبتمبر 2023 – أكتوبر 2024',
   hire='نوفمبر 2024',gap='+1 من إتمام معسكر T5 (و+12 من شهادة LLM Practitioner)',
   exp='LLM Practitioner (سبتمبر–نوفمبر 2023) · محلل بيانات — شركة كدانة للتنمية والتطوير، مشروع مالك (Full-time، أبريل–يوليو 2024) · Data Science and AI Trainee — T5 Bootcamp by SDAIA بتنفيذ أكاديمية طويق (يوليو–أكتوبر 2024) · Data Consultant — Devoteam (Full-time، منذ نوفمبر 2024)'),
 626:dict(slug='eng-noura-alghonaim-99a562194',ar='نورة غنيم الغنيم',en='Noura AlGhonaim',year=2023,org='Netways',role='مهندسة ذكاء اصطناعي (Artificial Intelligence Engineer)',
   program='معسكر تعلم الآلة + شهادة ممارس تعلم الآلة ML Practitioner — أكاديمية سدايا',period='سبتمبر–نوفمبر 2023',
   hire='ديسمبر 2023',gap='+1',
   exp='Machine Learning Bootcamp trainee — SDAIA (سبتمبر–أكتوبر 2023) · Artificial Intelligence Engineer — Netways (ديسمبر 2023 – أكتوبر 2024) · Business Analyst — Netways (Full-time، أكتوبر 2024 – ديسمبر 2025)'),
 2398:dict(slug='dina-bokhamseen-a6a50727a',ar='دينا بوخمسين',en='Dina Bokhamseen',year=2023,org='Accenture',role='محللة بيانات وذكاء اصطناعي (Data & AI Analyst)',
   program='معسكر T5 لعلوم البيانات والذكاء الاصطناعي — أكاديمية سدايا',period='ديسمبر 2023',
   hire='أبريل 2024',gap='+4',
   exp='Data & AI Analyst — Accenture Middle East (Full-time، أبريل 2024 – فبراير 2026) · Business Analyst — شركة حمد محمد الرقيب وأولاده (منذ أبريل 2026)'),
 2450:dict(slug='hassn-alqaeri-190a29225',ar='حسن القعري',en='Hassn Alqaeri',year=2024,org='جهة حكومية',role='مهندس ذكاء اصطناعي (AI Engineer)',
   program='معسكر النماذج اللغوية الكبيرة (ديسمبر 2023) + معسكر T5 لعلوم البيانات (مارس–يونيو 2024) — أكاديمية سدايا',period='ديسمبر 2023 – يونيو 2024',
   hire='أبريل 2025',gap='+10 من إتمام معسكر T5',
   exp='SDAIA T5 Data Science Bootcamp بتنفيذ أكاديمية طويق (مارس–يونيو 2024) · AWS Solutions Architect Bootcamp (يونيو–يوليو 2024) · AI Engineer — Stealth Startup (تدريب، يونيو–سبتمبر 2024؛ لا يُحتسب) · AI Engineer — Confidential Government (Full-time، منذ أبريل 2025)'),
 2475:dict(slug='maha-aladwani-37359b188',ar='مها العدواني',en='Maha Aladwani',year=2022,org='صندوق الاستثمارات العامة (PIF)',role='محللة بيانات (Data Analyst — عقد)',
   program='معسكر T5 لعلوم البيانات — أكاديمية سدايا',period='نوفمبر 2021 – يناير 2022',
   hire='مارس 2022',gap='+2',
   exp='Data Scientist — SDAIA (تدريب المعسكر، نوفمبر 2021 – يناير 2022) · Data Analyst — Public Investment Fund (PIF) · Contract (مارس–أبريل 2022) · Accountant — Tamheer, Rodyan (مايو–نوفمبر 2022) · GDP — بناء الكفاءات، هيئة الزكاة والضريبة والجمارك (فبراير 2023) · Mobility Specialist ثم Mobility Senior Specialist — ZATCA'),
 2495:dict(slug='elaf-talal-226a901a8',ar='إيلاف طلال',en='Elaf Talal',year=2022,org='Devoteam',role='مستشارة ذكاء اصطناعي (AI Consultant)',
   program='معسكر T5 لعلوم البيانات والذكاء الاصطناعي — أكاديمية سدايا',period='أكتوبر 2021 – يناير 2022',
   hire='أغسطس 2022',gap='+7',
   exp='Artificial Intelligence Engineer — SDAIA Academy (المعسكر، أكتوبر 2021 – يناير 2022) · AI Consultant — Devoteam (Full-time، أغسطس 2022 – يوليو 2026) · AI Governance Consultant — Devoteam (يناير–سبتمبر 2026)'),
 2633:dict(slug='wejdan-mangl-9278b9104',ar='وجدان منقل',en='Wejdan Mangl',year=2022,org='علم (Elm)',role='محللة بيانات (Data Analyst)',
   program='أبطال صيف الذكاء الاصطناعي — أكاديمية سدايا',period='يوليو 2022',
   hire='أغسطس 2023',gap='+13',
   exp='Business Intelligence Developer — Panda Retail (Savola) (Full-time، مايو 2022 – أبريل 2023؛ سابق للإتمام) · Data Analyst — Elm (Full-time، أغسطس 2023 – يونيو 2025) · Senior Data Analyst — Elm (منذ يونيو 2025)'),
 2638:dict(slug='abdulrahman-alghofaily',ar='عبدالرحمن الغفيلي',en='Abdulrahman AlGhofaily',year=2023,org='GeoTech',role='عالم بيانات (Data Scientist)',
   program='معسكر T5 لعلوم البيانات والذكاء الاصطناعي — أكاديمية سدايا',period='سبتمبر–ديسمبر 2023',
   hire='يناير 2024',gap='+1',
   exp='Data Scientist — T5, SDAIA (تدريب، سبتمبر–ديسمبر 2023) · Tuwaiq Academy (دوام جزئي، ديسمبر 2023 – يناير 2024) · Data Scientist — GeoTech (Full-time، يناير 2024 – ديسمبر 2025) · Artificial Intelligence Engineer — GeoTech (منذ يناير 2026)'),
}
HOLD={
 282:'Innovation Senior Specialist لدى «Confidential Government» (يناير 2026، +11 من إتمام برنامج NVIDIA فبراير 2025) — ترقية داخلية في التحول الرقمي؛ الصلة بالتدريب (§5-و) غير محسومة والجهة غير مُفصح عنها.',
 1007:'محللة بيانات وأخصائية محتوى محلي — معادن (Full-time، ديسمبر 2024؛ ضمن النافذة أيًا كان شهر إتمام 2024). المسمى مزدوج والوصف يغلب عليه برنامج تطوير الموردين؛ الصلة (§5-و) تحتاج حكمًا.',
 1494:'برنامج المصرفي المستقبلي (GDP) — مصرف الإنماء، مكافحة الاحتيال (فبراير 2025، +3)؛ هل يُحتسب برنامج تطوير الخريجين توظيفًا، وصلة التحليل الاحتيالي بالتدريب؟ ثم Fraud Analyst فبراير 2026 (+15، خارج النافذة).',
 2117:'Data Science & AI Engineer — أجير: دوام جزئي منذ سبتمبر 2025 (قبل المعسكر وخلاله) ثم دوام كامل مايو 2026 (+3). التحويل إلى دوام كامل لدور سابق للتدريب — النسبة إلى التدريب تحتاج حكمًا.',
 2238:'Data Scientist — المدفوعات السعودية (Full-time، يناير 2022). شهر الإتمام متعارض: فصل C04 = سبتمبر–نوفمبر 2021 (+2) بينما يُنهي إدخاله في سدايا يناير 2022 (الشهر نفسه — يُرجأ). يحتاج تأكيد شهر الإتمام من الأكاديمية.',
 2266:'Banker Technologist Program — البنك السعودي الفرنسي (Full-time، أبريل 2025، +6 من T5 أكتوبر 2024) — برنامج تطوير خريجين تقني؛ الصلة بالتدريب وعدّ GDP توظيفًا يحتاجان حكمًا.',
}
FAIL={
 170:'FAIL_TIMING — AFAAQ GDP لدى سند (يناير 2026، +15)؛ تدريب SAP وتدريب تحليل بيانات الموارد البشرية (نوفمبر 2025) لا يُحتسبان.',
 172:'FAIL_TIMING — Tamheer تحليل بيانات SSCL (سبتمبر 2026، +23).',
 177:'FAIL_NO_OUTCOME — لا خبرة بعد معسكر T5 (أكتوبر 2024).',
 260:'FAIL_TIMING — تدريب محلل بيانات لدى علم (يونيو 2025) تدريبٌ وخارج النافذة.',
 396:'FAIL_NO_OUTCOME — تدريب KACST التعاوني (يناير–أبريل 2025) سابق للإتمام (ديسمبر 2025).',
 429:'FAIL_NO_OUTCOME — لا خبرة بعد الإتمام.',
 495:'FAIL_NO_OUTCOME — لا خبرة بعد الإتمام (LLM Practitioner نوفمبر–ديسمبر 2023).',
 528:'FAIL_INTERN — Data Science Intern لدى SGS (يوليو–أغسطس 2024) تدريب لا يُحتسب.',
 557:'NO_EXPERIENCE — صفحة الخبرة فارغة.',
 565:'FAIL_INTERN — أدوار «AI Intern» (Creative Hospitality مايو 2024، أرامكو يناير 2025) تدريبات لا تُحتسب.',
 624:'FAIL_NO_OUTCOME — معسكرات لاحقة فقط (أكاديمية سعودية رقمية).',
 656:'FAIL_INTERN — AI Trainee لدى أكاديمية كاوست (يناير–مارس 2024) تدريب.',
 815:'FAIL_NO_OUTCOME — لا خبرة بعد الإتمام.',
 829:'FAIL_TIMING — محللة بيانات Tamheer لدى بوبا (يوليو 2025) خارج نافذة إتمام الربع الأول 2024؛ تدريبات سابقة لا تُحتسب.',
 919:'FAIL_PRIOR — مدربة في المؤسسة العامة للتدريب التقني منذ 2019 (سابق).',
 985:'FAIL_TIMING — AI Engineer لدى Markineer (سبتمبر 2025) خارج النافذة؛ العمل الحر (سبتمبر 2024) لا يُعد دليلًا موثوقًا.',
 1052:'FAIL_INTERN — Le Wagon (تدريب، أغسطس 2025). شهر الإتمام من صفحتها: فبراير 2024.',
 1078:'FAIL_TIMING — Darb Alwatan (مايو 2025) لا يمكن تثبيته داخل النافذة لأن شهر الإتمام غير محدد (الربع الأول 2024).',
 1092:'FAIL_TIMING — Business Analyst لدى العبيكان الصحية (سبتمبر 2025) خارج النافذة؛ تدريبات تقنية المعلومات لا تُحتسب.',
 1100:'NO_EXPERIENCE — صفحة الخبرة فارغة.',
 1224:'FAIL_RELATEDNESS — QA Tester لدى Mirai (فبراير 2025). صفحتها تُظهر برنامج T5 (يوليو–أكتوبر 2024).',
 1238:'FAIL_TIMING — NWC (سبتمبر 2025، +19)؛ Accenture سابقة (يوليو 2023). شهر الإتمام من صفحتها: فبراير 2024.',
 2099:'NO_OUTCOME_YET — لا خبرة بعد فبراير 2026 (النافذة مفتوحة حتى أبريل 2027).',
 2100:'NO_EXPERIENCE — صفحة الخبرة فارغة.',
 2126:'NO_OUTCOME_YET — معسكر Meta بأكاديمية طويق (يوليو 2026) فقط.',
 2131:'NO_OUTCOME_YET — تدريبات سابقة فقط.',
 2265:'FAIL_NO_OUTCOME — لا خبرة بعد T5 (أكتوبر 2024)؛ Tamheer سابق.',
 2342:'FAIL_RELATEDNESS — Business Analysis Specialist لدى Deloitte (مايو 2024، +5) في أنظمة ERP — ليس دور بيانات/ذكاء اصطناعي.',
 2399:'FAIL_TIMING — مستشارة SAP لدى NCGR (نوفمبر 2025) خارج النافذة وغير ذي صلة.',
 2409:'FAIL_RELATEDNESS — Product Analyst (يونيو 2022) لدى وزارة الثقافة/تكامل — تحليل منتجات لا دور بيانات.',
 2535:'FAIL_PRIOR — محللة بيانات في وزارة البلديات والإسكان منذ نوفمبر 2021 (سابق للمعسكر).',
 2560:'FAIL_INTERN — تدريب دعم التطبيقات لدى وزارة الاقتصاد (سابق).',
 2634:'FAIL_RELATEDNESS — Quality Assurance Specialist ثم Business Analyst لدى ولاء للتأمين.',
 2635:'FAIL_TIMING — Petrolube (فبراير 2025، +16)؛ Le Wagon تدريب.',
 2636:'FAIL_RELATEDNESS — أخصائية مخاطر واستمرارية أعمال لدى وزارة الاتصالات (مارس 2025).',
 2660:'FAIL_NO_OUTCOME — لا خبرة بعد المعسكر.',
 2673:'FAIL_HOSTORG — إدخال «Junior Data Scientist — SDAIA» يبدأ مع المعسكر (أكتوبر 2021)، لا توظيف لاحق مستقل.',
 2683:'FAIL_NO_OUTCOME — لا خبرة بعد المعسكر.',
 2685:'FAIL_NO_OUTCOME — لا خبرة بعد المعسكر.',
}
UNREAD=[686,2268]
