"""Module 3 — pytest-style tests for `src/rafeeq/tools/*.py`.

Covers, per the module package's Lab 3 expected outputs and SPEC §8: bad
id format, not found, happy path per tool, the error-as-value contract
(never a raise), and idempotent refund. Run with `pytest -q` where pytest
is available (the classroom container); `tests/unit/run_without_pytest.py`
exercises the SAME assertions with stdlib `unittest` for environments
(like this build sandbox, SPEC §1) where pytest cannot be installed —
keep the two in sync when adding a case.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SRC = _REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from rafeeq.adapters.store import store
from rafeeq.tools.billing import (
    get_invoice_impl,
    get_payment_impl,
    issue_refund_impl,
    mark_refunded_impl,
)
from rafeeq.tools.customer import (
    add_case_note_impl,
    get_customer_impl,
    get_customer_tickets_impl,
)
from rafeeq.tools.logistics import (
    estimate_eta_impl,
    find_delivery_exception_impl,
    get_delivery_events_impl,
    get_driver_status_impl,
    reschedule_delivery_impl,
)
from rafeeq.tools.logistics import track_shipment_impl as logistics_track_shipment_impl
from rafeeq.tools.orders import get_order_impl, get_order_items_impl, list_orders_impl
from rafeeq.tools.tawseel import track_shipment_impl

# Fixed, real seed records (data/*.json as generated by data/generate.py) —
# picked once here so every test below is deterministic and does not
# depend on iteration order over the 2000-order seed file.
ORDER_ID = "TW-2026-10002"          # customer_id CUST-4144, delivered, amount 35.0 SAR
ORDER_CUSTOMER_ID = "CUST-4144"
PAYMENT_ID = "PAY-110002"
EXCEPTION_ORDER_ID = "TW-2026-10206"  # status "exception", has an exception event
DRIVER_ID = "DRV-254"
RESCHEDULABLE_ORDER_ID = "TW-2026-10030"  # status "in_transit" in the seed
TICKETED_CUSTOMER_ID = "CUST-1045"  # has exactly one synthetic open ticket


@pytest.fixture(autouse=True)
def _reset_store():
    """Every test starts from the seed data and leaves it that way —
    mutation from a WRITE-tool test (refund/reschedule/case-note) must
    never leak into the next test (mirrors `TawseelStore.snapshot`/
    `restore`'s whole reason for existing)."""
    store.reset()
    yield
    store.reset()


# --------------------------------------------------------------------------
# tawseel.py — the canonical worked example
# --------------------------------------------------------------------------
class TestTawseelTrackShipment:
    def test_bad_id_format_is_a_returned_error_not_a_raise(self):
        result = track_shipment_impl("not-an-order-id")
        assert result == {"error": "invalid_order_id_format"}

    def test_not_found_is_a_returned_error_not_a_raise(self):
        result = track_shipment_impl("TW-2026-00000")
        assert result == {"error": "order_not_found"}

    def test_happy_path(self):
        result = track_shipment_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert result["status"] == "delivered"
        assert "error" not in result


# --------------------------------------------------------------------------
# orders.py
# --------------------------------------------------------------------------
class TestOrdersTools:
    def test_get_order_bad_format(self):
        assert get_order_impl("garbage") == {"error": "invalid_order_id_format"}

    def test_get_order_not_found(self):
        assert get_order_impl("TW-2026-00000") == {"error": "order_not_found"}

    def test_get_order_happy_path(self):
        result = get_order_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert result["customer_id"] == ORDER_CUSTOMER_ID

    def test_list_orders_bad_format(self):
        assert list_orders_impl("nope") == {"error": "invalid_customer_id_format"}

    def test_list_orders_unknown_customer_is_empty_not_an_error(self):
        result = list_orders_impl("CUST-0000")
        assert result == {"customer_id": "CUST-0000", "orders": []}

    def test_list_orders_happy_path(self):
        result = list_orders_impl(ORDER_CUSTOMER_ID)
        assert any(o["order_id"] == ORDER_ID for o in result["orders"])

    def test_get_order_items_happy_path(self):
        result = get_order_items_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert isinstance(result["items_count"], int)


# --------------------------------------------------------------------------
# logistics.py
# --------------------------------------------------------------------------
class TestLogisticsTools:
    def test_track_shipment_bad_format(self):
        assert logistics_track_shipment_impl("garbage") == {"error": "invalid_order_id_format"}

    def test_track_shipment_not_found(self):
        assert logistics_track_shipment_impl("TW-2026-00000") == {"error": "order_not_found"}

    def test_track_shipment_happy_path(self):
        result = logistics_track_shipment_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert "status" in result

    def test_estimate_eta_happy_path(self):
        result = estimate_eta_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert "eta_iso" in result

    def test_estimate_eta_not_found(self):
        assert estimate_eta_impl("TW-2026-00000") == {"error": "order_not_found"}

    def test_get_delivery_events_happy_path(self):
        result = get_delivery_events_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID
        assert isinstance(result["events"], list) and len(result["events"]) > 0

    def test_get_driver_status_bad_format(self):
        assert get_driver_status_impl("nope") == {"error": "invalid_driver_id_format"}

    def test_get_driver_status_happy_path(self):
        result = get_driver_status_impl(DRIVER_ID)
        assert result["courier_id"] == DRIVER_ID

    def test_find_delivery_exception_found(self):
        result = find_delivery_exception_impl(EXCEPTION_ORDER_ID)
        assert result["order_id"] == EXCEPTION_ORDER_ID
        assert result["exception_code"] is not None

    def test_find_delivery_exception_none(self):
        result = find_delivery_exception_impl(ORDER_ID)
        assert result["exception_code"] is None

    def test_reschedule_delivery_not_found(self):
        assert reschedule_delivery_impl("TW-2026-00000", "2026-05-01T18:00:00+03:00") == {"error": "order_not_found"}

    def test_reschedule_delivery_not_reschedulable(self):
        result = reschedule_delivery_impl(ORDER_ID, "2026-05-01T18:00:00+03:00")  # ORDER_ID is delivered
        assert result["error"] == "not_reschedulable"

    def test_reschedule_delivery_happy_path(self):
        new_time = "2026-05-01T18:00:00+03:00"
        result = reschedule_delivery_impl(RESCHEDULABLE_ORDER_ID, new_time)
        assert result["rescheduled"] is True
        assert result["promised_at_after"] == new_time


# --------------------------------------------------------------------------
# billing.py
# --------------------------------------------------------------------------
class TestBillingTools:
    def test_get_invoice_happy_path(self):
        result = get_invoice_impl(ORDER_ID)
        assert result["order_id"] == ORDER_ID

    def test_get_invoice_not_found(self):
        assert get_invoice_impl("TW-2026-00000") == {"error": "order_not_found"}

    def test_get_payment_bad_format(self):
        assert get_payment_impl("nope") == {"error": "invalid_payment_id_format"}

    def test_get_payment_happy_path(self):
        result = get_payment_impl(PAYMENT_ID)
        assert result["payment_id"] == PAYMENT_ID

    def test_issue_refund_missing_idempotency_key(self):
        result = issue_refund_impl(ORDER_ID, 10.0, "goodwill", "")
        assert result == {"error": "missing_idempotency_key"}

    def test_issue_refund_invalid_amount(self):
        result = issue_refund_impl(ORDER_ID, 0.0, "goodwill", "key-1")
        assert result == {"error": "invalid_amount"}

    def test_issue_refund_order_not_found(self):
        result = issue_refund_impl("TW-2026-00000", 10.0, "goodwill", "key-1")
        assert result == {"error": "order_not_found"}

    def test_issue_refund_is_idempotent_by_key(self):
        """The idempotency contract, SPEC §7 mistake #5: retrying with the
        SAME key must never double-refund."""
        first = issue_refund_impl(ORDER_ID, 5.0, "goodwill", "same-key")
        second = issue_refund_impl(ORDER_ID, 5.0, "goodwill", "same-key")
        assert first["idempotent_replay"] is False
        assert second["idempotent_replay"] is True
        assert first["amount_sar"] == second["amount_sar"] == 5.0
        # a THIRD call with a genuinely different key is a new refund
        third = issue_refund_impl(ORDER_ID, 5.0, "goodwill", "different-key")
        assert third["idempotent_replay"] is False
        assert third["total_refunded_sar"] == 10.0

    def test_issue_refund_flags_human_approval_above_limit(self):
        result = issue_refund_impl("TW-2026-23560", 970.36, "damaged", "big-refund-key")
        assert result["requires_human_approval"] is True

    def test_mark_refunded_bad_format(self):
        assert mark_refunded_impl("nope", 10.0) == {"error": "invalid_order_id_format"}

    def test_mark_refunded_happy_path(self):
        result = mark_refunded_impl(ORDER_ID, 15.0)
        assert result["refunded"] is True
        assert result["refund_amount_sar"] == 15.0


# --------------------------------------------------------------------------
# customer.py
# --------------------------------------------------------------------------
class TestCustomerTools:
    def test_get_customer_bad_format(self):
        assert get_customer_impl("nope") == {"error": "invalid_customer_id_format"}

    def test_get_customer_not_found(self):
        assert get_customer_impl("CUST-0000") == {"error": "customer_not_found"}

    def test_get_customer_happy_path(self):
        result = get_customer_impl(ORDER_CUSTOMER_ID)
        assert result["customer_id"] == ORDER_CUSTOMER_ID
        # never leaks an unmasked national id
        assert result["national_id_masked"].startswith("1X")

    def test_get_customer_tickets_happy_path(self):
        result = get_customer_tickets_impl(TICKETED_CUSTOMER_ID)
        assert result["customer_id"] == TICKETED_CUSTOMER_ID
        assert len(result["tickets"]) >= 1

    def test_add_case_note_ticket_not_found(self):
        result = add_case_note_impl(TICKETED_CUSTOMER_ID, "TKT-99999999", "note")
        assert result == {"error": "ticket_not_found"}

    def test_add_case_note_happy_path(self):
        ticket_id = get_customer_tickets_impl(TICKETED_CUSTOMER_ID)["tickets"][0]["ticket_id"]
        result = add_case_note_impl(TICKETED_CUSTOMER_ID, ticket_id, "resolved on first contact")
        assert "resolved on first contact" in result["notes"]


# --------------------------------------------------------------------------
# error-as-value contract (SPEC §7 mistake #4) — cross-cutting
# --------------------------------------------------------------------------
class TestErrorsAreValuesNotRaises:
    """None of these calls should ever raise — a bad id must come back as
    {"error": ...}, never an exception the agent loop has to catch."""

    @pytest.mark.parametrize(
        "fn,args",
        [
            (track_shipment_impl, ("bad",)),
            (get_order_impl, ("bad",)),
            (list_orders_impl, ("bad",)),
            (get_order_items_impl, ("bad",)),
            (logistics_track_shipment_impl, ("bad",)),
            (estimate_eta_impl, ("bad",)),
            (get_delivery_events_impl, ("bad",)),
            (get_driver_status_impl, ("bad",)),
            (find_delivery_exception_impl, ("bad",)),
            (reschedule_delivery_impl, ("bad", "2026-01-01T00:00:00+03:00")),
            (get_invoice_impl, ("bad",)),
            (get_payment_impl, ("bad",)),
            (issue_refund_impl, ("bad", 10.0, "x", "k")),
            (mark_refunded_impl, ("bad", 10.0)),
            (get_customer_impl, ("bad",)),
            (get_customer_tickets_impl, ("bad",)),
        ],
    )
    def test_bad_input_never_raises(self, fn, args):
        result = fn(*args)
        assert isinstance(result, dict) and result.get("error")
