AR={}
for line in '''Meshal-Css=مشعل الدلبحي
alghamdidata=عبدالرحمن الغامدي
hind190=هند الواصل
shahadalyahya04=شهد اليحيى
BothainahIbrahim=بثينة إبراهيم
noufsaad1987=نوف الربيعي
Amal-AlSaadoun=أمل السعدون
salman1-source=سلمان عابد
aleenTF=آلين الفوزان
Dana-Mutairi=دانة المطيري
csifaris=فارس المشرفي
halaalhamzah=هلا الحمزة
Bassam-bulaihi=بسام البليهي
raghada30=رغد العقيل
YasserAlasiri=ياسر أحمد العسيري
falhajlah-svg=فهد المطيري
wajennaif=وجن المطرفي
Rawan-Alahmadi=روان الأحمدي
NouraAlqasim=نورة علي القاسم
samary12=سمري العثمان
Yousef0197=يوسف المطيري
dhaykh2006-dot=ضي الفوزان
renad-ebnalameer=رناد ابن الأمير
dalrashed112=ديمة الراشد
cyAlJoharah=الجوهرة القحطاني
EsshaqAlamer=إسحاق العامر
mohamedguesmi1992-gif=عوض محمد الهاجري
rayanf55=ريان فيصل أبو درمان
badrnn990=بدر العتيبي
razanalragas-stack=رزان الرقاص
shjg77=شهد الشهري
Anfal0az=أنفال البجير
SaadAlmuteri=سعد ناصر المطيري
Nony-911=نورة البقمي
itarfah=طرفة أحمد العامر
RetajSWE=رتاج الشعيبان
Mashae1l=مشاعل المفلح
FullyJory=جوري الشعلان
alsreem=ريم السبيعي
ItsDanah=دانة الفراج
nouf26702670=نوف الديري
aleen7-alle=آلين محمد
wateenaltrky=وتين التركي
Bariah10=بارعة الطيار
danl32=دانة عبدالعزيز الدهيني
Hajaralshammari=هاجر الشمري
rakansaeed-1=راكان سعيد الشهراني
fajeralboqami=فجر البقمي
manaralbader=منار البدر
4erh=جوان التميمي
Almejelf=فيصل المجيل
amalaljauid0=أمل العتيبي
Hakeemmidan=عبدالحكيم الميدان
Nouraaabdullah=نورة المعضي
Abdulel3h=عبدالإله الخثعمي
abdulaziizm2005=عبدالعزيز المشيقح
Salmaralfehaid=سلمى الفهيد'''.splitlines():
    k,v=line.split('='); AR[k]=v
for line in '''xro1dtcd=أروى عبدالرحمن أبو فياض
Eng-waadALqahtani=وعد ناصر القحطاني
assirims=محمد عسيري
9n7yr77p27-ossf=نورة اليوسف
LayanAlrouji=ليان الروجي
ahmed-alsahli=أحمد السهلي
jojoAlajmi=الجوهرة العجمي
faisalalshehri856=فيصل عمر الشهري
justwasaiff-stack=وصايف حمود
Haneenalq1=حنين عبدالله القحطاني
oykh2005-coder=عمر يوسف الحربي
ghkhadija1995-dot=خديجة الدوسري
lojainAbdulaziz=لجين عبدالعزيز العمري
Lobaali=لبى علي اليحيى
Hamed1418=حامد الرشيدي
saud1427446=سعود إبراهيم الدعيب
hend07=هند الغريبي
NawafAlbogami=نواف البقمي
azshahrany=عبدالعزيز سعيد تركي الشهراني
Shrouqalzah=شروق الزهراني
20noura01-hash=نورة المحسن
AhmedAI777=أحمد سعيد
dunash12=دنى شليه القحطاني
halmubeareek-svg=حصة المبيريك
reemalialqarni=ريم القرني
Ghaida-aldrees=غيداء الدريس
GhofranAT=غفران آل توفيق
hanan27=حنان أحمد الأحمدي
AfnanR11=أفنان عبدالله الجهني
Ghalao3=غلا العتيبي
lelesaad=ليان سعد
perdio-67=محمد السيد
abdullahalsabhana923-stack=عبدالله السبهان
k-alh=نايف الصماري
dxi7=دينا المطيري
LamisAlamrah=لميس العمرة
muhannad2-code=مهند الجعيد
alotaibisara=سارة العتيبي
Ayshamjaa=عائشة الجعفري
asma61044-art=أسماء القحطاني
mssh277=محمد الحازمي
Monasalamri=منى العمري
wafaa1420=وفاء المطيري
lologhost3=ليان الحمد
Mrsos07=سعود الغامدي
Nasser-Alsuduni0=ناصر السدوني
AhmedAlmufarriji=أحمد المفرجي
ziyadaljohanii=زياد عبدالله الجهني
nawaf-ds=نواف السليس
M9790DS=مروة الرسيني
Maymonah98=ميمونة الثنيان
iesmur=رغد العنزي
sara-010=سارة الضويان
fatemah-taw=فاطمة توفيق
Areej-almutairi=أريج المطيري
shathasultan=شذى سلطان السويلم'''.splitlines():
    k,v=line.split('='); AR[k]=v
VERIFIED_AR={'abdulaziizm2005','jojoAlajmi','NawafAlbogami','Monasalamri'}
