/* =========================================================
   SDAIA Academy — Graduate Success Stories · Data
   المصدر: تقرير أفضل 20 قصة نجاح (30 يوليو 2026)
   ========================================================= */
'use strict';

const SITE_STATS = [
  { value: 2166, label: 'خريجًا وخريجة موثّقين', note: 'قاعدة البيانات الموحّدة — يوليو 2026' },
  { value: 183,  label: 'جهة عمل موثّقة',        note: 'قطاعات حكومية وخاصة وعالمية' },
  { value: 36,   label: 'مخرجًا بحثيًا',          note: 'أوراق منشورة ومخرجات علمية' },
  { value: 16,   label: 'موقعًا قياديًا',          note: 'رئاسة أقسام وقطاعات وفرق' },
];

const EXTRA_STATS = [
  { value: 212, label: 'خريج برامج NVIDIA المعتمدة' },
  { value: 165, label: 'نتيجة توظيف مرصودة' },
  { value: 13,  label: 'صلة موثّقة بشركات ناشئة' },
  { value: 50,  label: 'نسبة النساء في قائمة العشرين ٪' },
];

const CATEGORIES = [
  { id: 'all',        label: 'الكل' },
  { id: 'employment', label: 'التوظيف والتقدم المهني' },
  { id: 'leadership', label: 'القيادة والمواقع الرفيعة' },
  { id: 'research',   label: 'البحث والنشر العلمي' },
  { id: 'opensource', label: 'المصادر المفتوحة' },
  { id: 'awards',     label: 'الجوائز والزمالات' },
  { id: 'startup',    label: 'ريادة الأعمال' },
];

const VERIFICATION = {
  'أ': { label: 'تحقق علني مستقل', desc: 'مصدران مستقلان على الأقل، أحدهما علني (موقع رسمي، ناشر علمي، واس، GitHub/HF).', color: '#104281' },
  'ب': { label: 'ملف رسمي + مؤشر علني', desc: 'بيانات الأكاديمية الرسمية تدعمها فهرسة عامة أو منشور ذاتي.', color: '#2a78d6' },
  'ج': { label: 'ملف رسمي داخلي', desc: 'موثوق مؤسسيًا وغير ظاهر علنيًا — النمط البنيوي الغالب في بيانات الخريجين.', color: '#6da7ec' },
};

const TIMELINE = [
  { year: '2021', title: 'انطلاقة الأكاديمية', text: 'إطلاق أكاديمية سدايا في يوليو 2021، وتخريج أول دفعة لعلوم البيانات بخمسة وثلاثين خريجًا في أكتوبر من العام نفسه.' },
  { year: '2023', title: 'معسكرات التخصص', text: 'معسكرات تعلم الآلة والنماذج اللغوية الكبيرة تُخرّج ممارسين متخصصين، وأول ملف رسمي موحّد للمجتازين.' },
  { year: '2024', title: 'عام T5 والتخريج الرسمي', text: 'معسكر T5 لعلوم البيانات، وتخريج 194 متدربًا في حفل رسمي وثّقته وكالة الأنباء السعودية، ومشاريع تخرج منشورة علنًا مثل RASYD وADEL.' },
  { year: '2025', title: 'إلى قلب المنظومة الوطنية', text: 'خريجون في HUMAIN وصندوق الاستثمارات العامة وJ.P. Morgan وسدايا نفسها، ومعسكرا هندسة البيانات وServiceNow، وزمالة قمم النخبوية.' },
  { year: '2026', title: 'أثر موثّق بالأرقام', text: 'قاعدة موحّدة تضم 2,166 خريجًا، و212 خريجًا لبرامج NVIDIA، وجولة تحقق علني مستقلة توثّق أفضل عشرين قصة نجاح.' },
];

const CATEGORY_COUNTS = [
  { label: 'التوظيف والتقدم المهني', count: 9 },
  { label: 'القيادة والمواقع الرفيعة', count: 3 },
  { label: 'البحث والنشر العلمي', count: 3 },
  { label: 'المصادر المفتوحة', count: 2 },
  { label: 'الجوائز والزمالات', count: 2 },
  { label: 'ريادة الأعمال', count: 1 },
];

const STORIES = [
  {
    rank: 1, id: 'khalid-alduwaysan',
    name: 'خالد الدويسان', nameEn: 'Khalid Alduwaysan',
    photo: 'assets/khalid-alduwaysan.jpg',
    role: 'مطوّر ذكاء اصطناعي ثم مهندس بيانات في جهة حكومية',
    org: 'أكاديمية الملك سلمان العالمية للغة العربية', orgLogo: null,
    program: 'معسكر T5 لعلوم البيانات والذكاء الاصطناعي',
    period: 'يوليو – أكتوبر 2024',
    score: 92, verification: 'أ',
    category: 'employment', categories: ['employment', 'opensource'],
    gender: 'm',
    impact: 'من التخرج إلى وظيفة «مطوّر ذكاء اصطناعي» خلال نحو ثلاثة أشهر موثّقة بالتواريخ — أقوى حالة في القاعدة كلها.',
    story: 'انتقل خالد من تخرّجه في معسكر T5 (أكتوبر 2024) إلى وظيفة مطوّر ذكاء اصطناعي في أكاديمية الملك سلمان العالمية للغة العربية اعتبارًا من يناير 2025 — أي خلال نحو ثلاثة أشهر فقط، موثقًا بالتواريخ على موقعه الشخصي. بنى نظام «رقيم» لتصحيح النص العربي (OCR + نماذج لغوية)، وشارك في مشروع التخرج RASYD لرصد مخالفات دراجات التوصيل (mAP50=0.711) المنشور تطبيقًا حيًّا، ثم واصل التعلم في معسكر هندسة البرمجيات بالأكاديمية السعودية الرقمية، ويعمل حاليًا مهندس بيانات في جهة حكومية.',
    achievements: ['توظيف موثّق بالتواريخ خلال ~3 أشهر من التخرج', 'نظام «رقيم» لتصحيح النص العربي (OCR + نماذج لغوية)', 'عضو فريق مشروع RASYD المنشور تطبيقًا حيًّا', 'مسار تعلم متواصل: معسكر هندسة برمجيات 2025'],
    links: [
      { label: 'الموقع الشخصي', url: 'https://duwaysan.github.io/portfolio/' },
      { label: 'GitHub', url: 'https://github.com/Duwaysan' },
      { label: 'مستودع RASYD', url: 'https://github.com/NasserAlsaqer/Detect-Violated-Motorbikes-Delivery-RASYD' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/kduwaysan/' },
    ],
  },
  {
    rank: 2, id: 'maha-thafar',
    name: 'د. مها ثفار', nameEn: 'Dr. Maha Thafar',
    photo: null,
    role: 'أستاذة مساعدة — قسم علوم الحاسب',
    org: 'جامعة الطائف', orgLogo: 'assets/taif-university.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: 'ديسمبر 2023',
    score: 90, verification: 'أ',
    category: 'research', categories: ['research'],
    gender: 'f',
    impact: 'أستاذة مساعدة وباحثة منشورة في Scientific Reports تختار برامج الأكاديمية لتحديث مهاراتها في النماذج اللغوية.',
    story: 'حاصلة على الدكتوراه من كاوست (مختبر CBRC للمعلوماتية الحيوية)، وأستاذة مساعدة بقسم علوم الحاسب في جامعة الطائف — مؤكدة على صفحة الجامعة الرسمية. باحثة منشورة بأوراق محكّمة بارزة في التنبؤ بالتفاعلات الدوائية: Affinity2Vec (Scientific Reports، 2022) وDTiGEMS+ وDTi2Vec. قصتها نموذج لالتقاء التأهيل الأكاديمي العميق ببرامج الأكاديمية: باحثة منشورة دوليًا تختار برنامج الأكاديمية تحديثًا لمهاراتها التطبيقية.',
    achievements: ['دكتوراه من كاوست — مختبر CBRC', 'أستاذة مساعدة بجامعة الطائف', 'Affinity2Vec منشورة في Nature Scientific Reports', 'أوراق DTiGEMS+ وDTi2Vec في التنبؤ بالتفاعلات الدوائية'],
    links: [
      { label: 'جامعة الطائف — هيئة التدريس', url: 'https://tu.edu.sa/En/Computer-Science/243/Pages/21459/Faculty-Members' },
      { label: 'Affinity2Vec — Nature', url: 'https://www.nature.com/articles/s41598-022-08787-9' },
      { label: 'كاوست CBRC', url: 'https://cemse.kaust.edu.sa/cbrc/people/person/maha-thafar' },
      { label: 'GitHub', url: 'https://github.com/MahaThafar' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/maha-abduljabbar-thafar-7957b36b/' },
    ],
  },
  {
    rank: 3, id: 'maha-altalak',
    name: 'مها الطلق', nameEn: 'Maha Altalak',
    photo: null,
    role: 'رئيسة قطاع نمذجة الذكاء الاصطناعي · مديرة الابتكار بوزارة الصحة',
    org: 'مستشفى صحة الافتراضي — وزارة الصحة', orgLogo: 'assets/moh.png',
    program: 'معسكر T5 لعلوم البيانات',
    period: '2021 – 2022',
    score: 86, verification: 'ب',
    category: 'leadership', categories: ['leadership'],
    gender: 'f',
    impact: 'من مشروع تنبؤ بأسعار العقارات في المعسكر إلى قيادة نمذجة الذكاء الاصطناعي في أكبر مستشفى افتراضي في العالم.',
    story: 'تقود مها قطاع نمذجة الذكاء الاصطناعي في مستشفى صحة الافتراضي التابع لوزارة الصحة — أكبر مستشفى افتراضي في العالم (موسوعة غينيس) — منذ 2024، وتشغل دور مديرة الابتكار بالوزارة منذ نوفمبر 2025. مسارها هو أعلى موقع قيادي موثّق لخريج معسكرات الأكاديمية في القطاع الصحي الحكومي، ويوثّق مستودعها على GitHub بداية الرحلة من معسكر T5.',
    achievements: ['رئيسة قطاع نمذجة الذكاء الاصطناعي — مستشفى صحة الافتراضي', 'مديرة الابتكار بوزارة الصحة منذ نوفمبر 2025', 'أكبر مستشفى افتراضي في العالم — موسوعة غينيس', 'أعلى موقع قيادي موثّق لخريجي المعسكرات في القطاع الصحي'],
    links: [
      { label: 'مستودع T5 — GitHub', url: 'https://github.com/Maha-Altalak/SDAIA-T5-Bootcamp' },
      { label: 'عن المستشفى — وزارة الصحة', url: 'https://www.moh.gov.sa/en/ministry/projects/pages/seha-virtual-hospital.aspx' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/mahaaltalak/' },
    ],
  },
  {
    rank: 4, id: 'jawaher-alghamdi',
    name: 'د. جواهر الغامدي', nameEn: 'Dr. Jawaher Alghamdi',
    photo: null,
    role: 'عضو هيئة تدريس وباحثة NLP',
    org: 'جامعة الملك خالد', orgLogo: 'assets/kku.png',
    program: 'برنامج NVIDIA المعتمد عبر الأكاديمية',
    period: '2024 – 2025',
    score: 85, verification: 'أ',
    category: 'research', categories: ['research', 'awards'],
    gender: 'f',
    impact: 'سجل نشر بحثي كثيف 2023–2026 في مجلات مصنفة، مع خمس شهادات NVIDIA واعتمادَي NVIDIA-Certified Associate.',
    story: 'عضو هيئة تدريس بجامعة الملك خالد، حاصلة على الدكتوراه من جامعة كوينزلاند، وصاحبة سجل نشر بحثي كثيف (2023–2026) في مجلات مصنفة: Expert Systems with Applications وKnowledge-Based Systems وEngineering Applications of AI في كشف الأخبار الزائفة ومعالجة اللغة، ومشاركة في PAKDD 2025 Doctoral Consortium. أتمّت خمس شهادات دورات في برنامج NVIDIA المعتمد عبر الأكاديمية وشهادتَي NVIDIA-Certified Associate، إلى جانب زمالة مسك وAWS AI/ML Scholar.',
    achievements: ['دكتوراه من جامعة كوينزلاند', 'نشر في Expert Systems with Applications وKnowledge-Based Systems', 'PAKDD 2025 Doctoral Consortium', '5 شهادات NVIDIA + شهادتا NVIDIA-Certified Associate'],
    links: [
      { label: 'DBLP', url: 'https://dblp.org/pid/214/6817.html' },
      { label: 'Google Scholar', url: 'https://scholar.google.com/citations?user=tAfpHygAAAAJ' },
      { label: 'PAKDD 2025', url: 'https://pakdd2025.org/doc/Consortium/Jawaher-Alghamdi-PAKDD25-DC.pdf' },
    ],
  },
  {
    rank: 5, id: 'wadha-almattar',
    name: 'د. وضحة المطر', nameEn: 'Dr. Wadha Almattar',
    photo: 'assets/wadha-almattar.jpg',
    role: 'أستاذة مساعدة ورئيسة قسم هندسة الحاسب',
    org: 'جامعة الإمام عبدالرحمن بن فيصل', orgLogo: null,
    program: 'برنامج NVIDIA المعتمد عبر الأكاديمية',
    period: '2024 – 2025',
    score: 82, verification: 'ب',
    category: 'leadership', categories: ['leadership', 'research'],
    gender: 'f',
    impact: 'رئاسة قسم هندسة الحاسب منذ أغسطس 2025، وتحت قيادة القسم أُطلق برنامج بكالوريوس الذكاء الاصطناعي.',
    story: 'أستاذة مساعدة بجامعة الإمام عبدالرحمن بن فيصل (صفحة رسمية مؤكدة)، ورئيسة قسم هندسة الحاسب منذ أغسطس 2025، وتحت قيادة القسم أُطلق برنامج بكالوريوس الذكاء الاصطناعي. خريجة كاوست وكفوبم وباحثة رؤية حاسوبية، أتمّت برنامج NVIDIA المعتمد عبر الأكاديمية وشهادتَي NVIDIA-Certified Associate (فبراير 2025).',
    achievements: ['رئيسة قسم هندسة الحاسب منذ أغسطس 2025', 'إطلاق برنامج بكالوريوس الذكاء الاصطناعي', 'باحثة رؤية حاسوبية — خريجة كاوست وكفوبم', 'شهادتا NVIDIA-Certified Associate'],
    links: [
      { label: 'صفحتها — جامعة الإمام عبدالرحمن', url: 'https://www.iau.edu.sa/en/colleges/college-of-computer-science-and-information-technology/faculty/wadha-muteb-al-mattar' },
      { label: 'Google Scholar', url: 'https://scholar.google.com/citations?user=k_AKQ9UAAAAJ' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/wadha-m-almattar-phd-93b92a186/' },
    ],
  },
  {
    rank: 6, id: 'aljawharah-bintamran',
    name: 'الجوهرة بن طمران', nameEn: 'Aljawharah Bin Tamran',
    photo: 'assets/aljawharah-bintamran.jpg',
    role: 'مهندسة ذكاء اصطناعي أولى (Senior AI Engineer)',
    org: 'HUMAIN — شركة الذكاء الاصطناعي الوطنية', orgLogo: 'assets/humain.png',
    program: 'برامج NVIDIA والذكاء الاصطناعي التوليدي',
    period: '2024',
    score: 80, verification: 'ج',
    category: 'leadership', categories: ['leadership', 'employment'],
    gender: 'f',
    impact: 'أعلى موقع موثّق لخريجة برامج الأكاديمية داخل الشركة الوطنية الرائدة للذكاء الاصطناعي المملوكة لصندوق الاستثمارات العامة.',
    story: 'تعمل الجوهرة مهندسة ذكاء اصطناعي أولى في HUMAIN — شركة الذكاء الاصطناعي الوطنية المملوكة لصندوق الاستثمارات العامة، المؤسسة في مايو 2025 برئاسة ولي العهد، وصاحبة نموذج ALLaM العربي وشراكات مع NVIDIA وAWS وMicrosoft. حازت شهادتَي NVIDIA-Certified Associate في Generative AI LLMs وMultimodal (2024). قصتها تجسّد وصول خريجي الأكاديمية إلى قلب المنظومة التي أُنشئت الأكاديمية لتغذيتها.',
    achievements: ['Senior AI Engineer في HUMAIN', 'شهادتا NVIDIA-Certified Associate: Generative AI LLMs وMultimodal', 'ضمن منظومة نموذج ALLaM العربي', 'شركة وطنية مملوكة لصندوق الاستثمارات العامة'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/aljawharah-bin-tamran-1121461a7/' },
      { label: 'HUMAIN — PIF', url: 'https://www.pif.gov.sa/en/our-investments/our-portfolio/humain/' },
    ],
  },
  {
    rank: 7, id: 'rayan-dahlawi',
    name: 'ريان دحلاوي', nameEn: 'Rayan Dahlawi',
    photo: 'assets/rayan-dahlawi.jpg',
    role: 'أخصائي علوم بيانات (AI/BI)',
    org: 'عبداللطيف جميل المتحدة للتمويل', orgLogo: 'assets/aljuf.png',
    program: 'معسكر النماذج اللغوية الكبيرة + دورات NVIDIA',
    period: 'ديسمبر 2023 – يوليو 2026',
    score: 79, verification: 'أ',
    category: 'employment', categories: ['employment', 'awards'],
    gender: 'm',
    impact: 'توظيف مؤكد من مصدرين مستقلين، مع خمس دورات NVIDIA معتمدة — الحالة التي حسمت مطابقة ALJUF في السجلات.',
    story: 'أخصائي علوم بيانات (AI/BI) في عبداللطيف جميل المتحدة للتمويل (ALJUF). انتسابه ونتيجته مؤكدان من مصدرين مستقلين: الملف الرسمي للمجتازين ومنشوره الذاتي الموسوم على LinkedIn — وهي الحالة التي حسمت مطابقة «ALJUF» في سجلات الأكاديمية ورفعت ثقتها من 30 إلى 88/100. حاز شهادة LLMs Practitioner (ديسمبر 2023) وخمس دورات NVIDIA معتمدة (يوليو 2026).',
    achievements: ['أخصائي علوم بيانات AI/BI في ALJUF', 'شهادة LLMs Practitioner', '5 دورات NVIDIA معتمدة', 'توثيق من مصدرين مستقلين'],
    links: [
      { label: 'منشور المعسكر — LinkedIn', url: 'https://www.linkedin.com/posts/rayan-dahlawi_llmbootcamp-ai-sdaia-activity-7139361304338710528-fzmC' },
    ],
  },
  {
    rank: 8, id: 'abdullah-alowayyid',
    name: 'عبدالله العويد', nameEn: 'Abdullah Alowayyid',
    photo: 'assets/abdullah-alowayyid.jpg',
    role: 'مهندس — مركز عمليات الشبكات',
    org: 'شركة سايت SITE', orgLogo: 'assets/site-co.png',
    program: 'معسكرا إدارة البيانات وتعلم الآلة + ممارس تعلم الآلة',
    period: '2023 – 2025',
    score: 78, verification: 'أ',
    category: 'employment', categories: ['employment'],
    gender: 'm',
    impact: 'توثيق مرتفع (92/100) بتطابق مستقل بين بيانات الأكاديمية والمقتطف العام لملفه المهني.',
    story: 'مهندس بمركز عمليات الشبكات في شركة سايت SITE منذ 2025، بعد اجتيازه معسكرَي إدارة البيانات وتعلم الآلة وبرنامج ممارس تعلم الآلة (2023). توثيقه من الأعلى في القاعدة (92/100) بفضل التطابق المستقل بين بيانات الأكاديمية والمقتطف العام لملفه المهني (سايت، جامعة القصيم، الرياض).',
    achievements: ['مهندس بمركز عمليات الشبكات — SITE', 'ثلاثة برامج مجتازة في 2023', 'توثيق بدرجة ثقة 92/100'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdullah-alowayid/' },
    ],
  },
  {
    rank: 9, id: 'abdulaziz-althumairy',
    name: 'عبدالعزيز التميري', nameEn: 'Abdulaziz Al-Thumairy',
    photo: 'assets/abdulaziz-althumairy.jpg',
    role: 'محلل أداء الاستثمارات — الشرق الأوسط وشمال أفريقيا',
    org: 'صندوق الاستثمارات العامة PIF', orgLogo: 'assets/pif.png',
    program: 'التدريب الاحترافي في النماذج اللغوية الكبيرة',
    period: '2024 – 2025',
    score: 77, verification: 'ب',
    category: 'employment', categories: ['employment'],
    gender: 'm',
    impact: 'من التدريب الاحترافي في النماذج اللغوية إلى تحليل أداء الاستثمارات في أكبر صناديق الثروة السيادية.',
    story: 'محلل أداء الاستثمارات لمنطقة الشرق الأوسط وشمال أفريقيا في صندوق الاستثمارات العامة PIF منذ 2025، بعد اجتيازه التدريب الاحترافي في النماذج اللغوية الكبيرة (2024). عملُه في الصندوق مؤكد عبر المقتطف العام لملفه المهني، وشارك في تنظيم فعالية PIF Digital & Technology Leaders Offsite 2026.',
    achievements: ['محلل أداء استثمارات في PIF', 'مشارك في تنظيم PIF Digital & Technology Leaders Offsite 2026'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdulaziz-al-thumairy/' },
    ],
  },
  {
    rank: 10, id: 'rana-alharsan',
    name: 'رنا الحرصان', nameEn: 'Rana al-Harsan',
    photo: 'assets/rana-alharsan.jpg',
    role: 'مشروع «رَكَّن» — ضمن أفضل المشاريع من بين 50',
    org: 'فضاء أجا لتقنية المعلومات', orgLogo: 'assets/aja-space.png',
    program: 'معسكر معالجة الازدحام المروري (360 ساعة) + معسكر T5',
    period: 'يوليو – أكتوبر 2024',
    score: 76, verification: 'أ',
    category: 'awards', categories: ['awards', 'employment'],
    gender: 'f',
    impact: 'ضمن دفعة الـ194 التي خرّجتها سدايا رسميًا بتوثيق واس، ومشروعها «رَكَّن» عُرض في حفل التخرج ضمن الأفضل.',
    story: 'ضمن دفعة الـ194 التي خرّجتها سدايا رسميًا في 31 أكتوبر 2024 بتوثيق وكالة الأنباء السعودية، بعد معسكر تقنيات معالجة الازدحام المروري بالبيانات والذكاء الاصطناعي (360 ساعة). اختير مشروعها «رَكَّن» ضمن أفضل المشاريع من بين 50 مشروعًا وعُرض في حفل التخرج، وتعمل لدى فضاء أجا لتقنية المعلومات.',
    achievements: ['مشروع «رَكَّن» ضمن أفضل المشاريع من 50', 'تخريج رسمي موثّق بخبر واس', 'معسكر 360 ساعة في معالجة الازدحام المروري'],
    links: [
      { label: 'خبر التخريج — واس', url: 'https://www.spa.gov.sa/N2199008' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/rana-al-harsan-1792b1257/' },
    ],
  },
  {
    rank: 11, id: 'fares-altoukhi',
    name: 'فارس الطوخي', nameEn: 'Fares Altoukhi',
    photo: 'assets/fares-altoukhi.jpg',
    role: 'نماذج عربية مفتوحة على Hugging Face',
    org: 'مساهم مفتوح المصدر — فريق RASYD', orgLogo: null,
    program: 'معسكر T5 — فريق RASYD',
    period: 'أكتوبر 2024',
    score: 75, verification: 'أ',
    category: 'opensource', categories: ['opensource'],
    gender: 'm',
    impact: 'أغنى بصمة مفتوحة المصدر في العيّنة: نماذج عربية مضبوطة منشورة بخدمة REST حية على السحابة.',
    story: 'صاحب أغنى بصمة مفتوحة المصدر في العيّنة: نماذج مضبوطة منشورة على Hugging Face باسمه — Finetuned MarBERT لتحليل المشاعر العربية وArsarcasm لكشف السخرية (مايو 2024) وSpace لمشروع T5 (أكتوبر 2024) — وخدمة REST على Google Cloud Run (SVM بدقة 89%، وMARBERTv2 بمعامل F1=0.83). إسهامه يسد فجوة عالمية معروفة في موارد اللغة العربية المفتوحة — أثر يتجاوز صاحبه إلى كل من يستخدم نماذجه.',
    achievements: ['نماذج MarBERT وArsarcasm منشورة على Hugging Face', 'خدمة REST حية على Google Cloud Run', 'دقة 89% (SVM) وF1=0.83 (MARBERTv2)', 'إسهام في موارد اللغة العربية المفتوحة'],
    links: [
      { label: 'Hugging Face', url: 'https://huggingface.co/TheKnight115' },
      { label: 'مستودع التحليل العاطفي', url: 'https://github.com/TheKnight909/Emotional-analysis' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/fares-altoukhi/' },
    ],
  },
  {
    rank: 12, id: 'tala-bakir',
    name: 'تالا بكر', nameEn: 'Tala Bakir',
    photo: 'assets/tala-bakir.jpg',
    role: 'زميلة زمالة قمم · مهندسة برمجيات',
    org: 'زمالة قمم (McKinsey) · شور العالمية للتقنية', orgLogo: 'assets/sure-global.svg',
    program: 'ممارس تعلم الآلة',
    period: 'ديسمبر 2023 – 2025',
    score: 73, verification: 'أ',
    category: 'awards', categories: ['awards', 'employment'],
    gender: 'f',
    impact: 'زميلة دفعة 2025 في زمالة قمم المدعومة من McKinsey — خمسون زميلًا يُنتقون من نحو 18 ألف متقدم.',
    story: 'زميلة زمالة قمم المدعومة من McKinsey & Company — دفعة 2025 المؤكدة على صفحة خريجي الزمالة الرسمية، حيث يُنتقى خمسون زميلًا فقط من نحو 18 ألف متقدم سنويًا، ما يجعلها من أكثر الزمالات القيادية انتقائية في المملكة. اجتازت برنامج ممارس تعلم الآلة (ديسمبر 2023)، وتعمل مهندسة برمجيات في شركة شور العالمية للتقنية.',
    achievements: ['زمالة قمم — دفعة 2025 (بدعم McKinsey)', 'انتقاء من بين ~18,000 متقدم', 'مهندسة برمجيات في شور العالمية'],
    links: [
      { label: 'خريجو قمم', url: 'https://qimam.com/sa/en/alumni/' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/tala-bakir/' },
    ],
  },
  {
    rank: 13, id: 'mohammed-almalki',
    name: 'محمد المالكي وفريق ADEL', nameEn: 'Mohammed Almalki & ADEL Team',
    photo: 'assets/mohammed-almalki.jpg',
    role: 'نظام ADEL للإشارات المرورية الذكية',
    org: 'فريق ADEL — معسكر T5', orgLogo: null,
    program: 'معسكر T5 — مشروع التخرج ADEL',
    period: 'أكتوبر 2024',
    score: 72, verification: 'أ',
    category: 'opensource', categories: ['opensource'],
    gender: 'm',
    impact: 'أعلى مشاريع التخرج تقييمًا في سجل المشروع (88/100) — منشور تطبيقًا تفاعليًا على Hugging Face Spaces.',
    story: 'قاد محمد المالكي فريق مشروع ADEL (مع محمد الرويس وخالد الغامدي ووليد الإخوان) — أعلى مشاريع التخرج تقييمًا في سجل المشروع (88/100): نظام إشارات مرورية ذكية بالرؤية الحاسوبية يجمع YOLOv8 وDeepSort وPaddleOCR بدقة كشف مركبات 92% ومحاكاة SUMO، منشور تطبيقًا تفاعليًا على Hugging Face Spaces مع عرض على YouTube.',
    achievements: ['أعلى تقييم لمشاريع التخرج: 88/100', 'YOLOv8 + DeepSort + PaddleOCR — دقة 92%', 'محاكاة SUMO وتطبيق تفاعلي منشور'],
    links: [
      { label: 'مستودع ADEL', url: 'https://github.com/iwm10/ADEL-System' },
      { label: 'التطبيق — HF Spaces', url: 'https://huggingface.co/spaces/M12ths/ADEL_app' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/mohammd-almalkii/' },
    ],
  },
  {
    rank: 14, id: 'weam-abbas',
    name: 'وئام عباس', nameEn: 'Weam Abbas',
    photo: 'assets/weam-abbas.jpg',
    role: 'مهندسة ذكاء اصطناعي (بعد ترقية موثّقة)',
    org: 'أمانة منطقة عسير', orgLogo: 'assets/aseer-municipality.png',
    program: 'معسكر تعلم الآلة + معسكر النماذج اللغوية',
    period: 'أكتوبر – ديسمبر 2023',
    score: 70, verification: 'ب',
    category: 'employment', categories: ['employment'],
    gender: 'f',
    impact: 'ترقية موثّقة بالتسلسل الزمني: محللة بيانات (2024) ثم مهندسة ذكاء اصطناعي (2025) — من أوضح حالات الترقية في القاعدة.',
    story: 'من أوضح حالات الترقية توثيقًا في القاعدة كلها: محللة بيانات لدى أمانة عسير في 2024، ثم مهندسة ذكاء اصطناعي في 2025 — إحدى إحدى‑عشرة حالة ترقية مرصودة، موثقة بثلاثة مصادر (الملف الرسمي 2023 + بطاقة تعريفية 2026 + ملف مهني). اجتازت معسكرَي تعلم الآلة (أكتوبر 2023) والنماذج اللغوية الكبيرة (ديسمبر 2023).',
    achievements: ['ترقية موثّقة: محللة بيانات ← مهندسة ذكاء اصطناعي', 'إحدى 11 حالة ترقية مرصودة في القاعدة', 'معسكران مجتازان في 2023'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/weam-abbas2/' },
    ],
  },
  {
    rank: 15, id: 'areej-showail',
    name: 'أريج شويل', nameEn: 'Areej Showail',
    photo: 'assets/areej-showail.jpg',
    role: 'مؤسِّسة مشاركة (Co-Founder)',
    org: 'شركة سِنابس Synapse', orgLogo: 'assets/synapse.png',
    program: 'ممارس تعلم الآلة + معسكر تعلم الآلة',
    period: 'أكتوبر – نوفمبر 2023',
    score: 69, verification: 'ج',
    category: 'startup', categories: ['startup'],
    gender: 'f',
    impact: 'إحدى ثلاث عشرة صلة ريادية موثّقة في القاعدة — وشركتها الناشئة تضم خريجتين للأكاديمية.',
    story: 'مؤسِّسة مشاركة لشركة سِنابس Synapse الناشئة وفق الملف الرسمي للمجتازين — إحدى ثلاث عشرة صلة ريادية موثّقة في القاعدة. تنضم إليها زميلتها أسماء حبادي (نائبة مدير التسويق في Synapse) من الملف نفسه، أي أن الشركة تضم خريجتين للأكاديمية. اجتازت أريج برنامج ممارس تعلم الآلة ومعسكر تعلم الآلة (2023).',
    achievements: ['مؤسِّسة مشاركة لشركة سِنابس', 'الشركة تضم خريجتين للأكاديمية', 'إحدى 13 صلة ريادية موثّقة'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/areej-showail/' },
    ],
  },
  {
    rank: 16, id: 'mohammed-althunayan',
    name: 'محمد الثنيان', nameEn: 'Mohammed AlThunayan',
    photo: 'assets/mohammed-althunayan.jpg',
    role: 'مهندس برمجيات (Software Engineer I)',
    org: 'J.P. Morgan', orgLogo: 'assets/jpmorgan.png',
    program: 'ممارس تعلم الآلة (Machine Learning Practitioner)',
    period: 'ديسمبر 2023',
    score: 68, verification: 'ب',
    category: 'employment', categories: ['employment'],
    gender: 'm',
    impact: 'أحد أوضح أمثلة الوصول إلى شركة عالمية من الطراز الأول بعد برامج الأكاديمية.',
    story: 'مهندس برمجيات (Software Engineer I) في J.P. Morgan وفق الملف الرسمي — أحد أوضح أمثلة وصول خريجي الأكاديمية إلى شركة عالمية من الطراز الأول. موقعه الشخصي يوثّق تخرجه في هندسة البرمجيات من جامعة الملك فهد للبترول والمعادن (2024) ومشاريعه: TaqaPay وTaskMaster وHealth Guard.',
    achievements: ['Software Engineer I في J.P. Morgan', 'بكالوريوس هندسة برمجيات — كفوبم 2024', 'مشاريع TaqaPay وTaskMaster وHealth Guard'],
    links: [
      { label: 'الموقع الشخصي', url: 'https://malthunayan.com' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/m-althunayan/' },
    ],
  },
  {
    rank: 17, id: 'hussein-mohsen',
    name: 'حسين محسن', nameEn: 'Hussein Mohsen',
    photo: null,
    role: 'مساعد تدريس ذكاء اصطناعي',
    org: 'أكاديمية كاوست', orgLogo: 'assets/kaust-academy.png',
    program: 'معسكر هندسة البيانات — 5 شهادات Microsoft',
    period: '2025',
    score: 67, verification: 'ج',
    category: 'research', categories: ['research', 'employment'],
    gender: 'm',
    impact: 'من بكالوريوس الذكاء الاصطناعي إلى مسار أكاديمي بحثي في مؤسسة نخبوية خلال سنة واحدة.',
    story: 'مساعد تدريس ذكاء اصطناعي في أكاديمية كاوست (2025) — تحوّل من بكالوريوس الذكاء الاصطناعي بجامعة الإمام عبدالرحمن (2024) إلى مسار أكاديمي بحثي في مؤسسة نخبوية خلال سنة واحدة، بعد اجتيازه معسكر هندسة البيانات ونيله خمس شهادات احترافية من Microsoft خلال المعسكر.',
    achievements: ['مساعد تدريس ذكاء اصطناعي — أكاديمية كاوست', '5 شهادات Microsoft احترافية خلال المعسكر', 'انتقال إلى المسار البحثي خلال سنة واحدة'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/hussain-mohsen/' },
    ],
  },
  {
    rank: 18, id: 'majd-alziyadi',
    name: 'مجد الزيادي', nameEn: 'Majd Alziyadi',
    photo: null,
    role: 'مطوّر تطبيقات',
    org: 'IBM', orgLogo: null,
    program: 'معسكر مطوري أنظمة ServiceNow — شهادتا CAD وCSA',
    period: '2025',
    score: 66, verification: 'ج',
    category: 'employment', categories: ['employment', 'awards'],
    gender: 'm',
    impact: 'من معسكر ServiceNow إلى تطوير التطبيقات في IBM بشهادتَي CAD وCSA.',
    story: 'مطوّر تطبيقات في IBM بعد اجتيازه معسكر مطوري أنظمة ServiceNow (2025) ونيله شهادتَي CAD (مطوّر تطبيقات معتمد) وCSA (مدير نظام معتمد). قصته ضمن نمط متكرر لخريجي معسكرات 2025 الذين ظهروا في GOSI وIBM وسدايا في العام ذاته — «معسكر ← وظيفة متخصصة خلال أشهر».',
    achievements: ['مطوّر تطبيقات في IBM', 'شهادتا ServiceNow: CAD + CSA', 'توظيف في سنة المعسكر نفسها'],
    links: [],
  },
  {
    rank: 19, id: 'hind-alhijailan',
    name: 'هند الحجيلان', nameEn: 'Hind Alhujailan',
    photo: 'assets/hind-alhijailan.jpg',
    role: 'مسؤولة تميز خدمات الحوسبة السحابية',
    org: 'سدايا', orgLogo: null,
    program: 'معسكر مطوري أنظمة ServiceNow — شهادتا CAD وCSA',
    period: '2025',
    score: 65, verification: 'ج',
    category: 'employment', categories: ['employment'],
    gender: 'f',
    impact: 'الدائرة تكتمل: الهيئة التي درّبتها وظّفتها — واحدة من أكثر من ثماني حالات توظيف موثّقة لخريجين داخل سدايا.',
    story: 'مسؤولة تميز خدمات الحوسبة السحابية في سدايا نفسها (2025) — الدائرة تكتمل: الهيئة التي درّبتها وظّفتها. وهي واحدة من أكثر من ثماني حالات توظيف موثّقة لخريجين داخل سدايا (معها دانة المديفر ونوف أبو حيمد ورغد القبالي ومحمد البريه وغيرهم — جميعهم «مهندسو ذكاء اصطناعي» بالملف الرسمي). اجتازت معسكر ServiceNow بشهادتَي CAD وCSA.',
    achievements: ['مسؤولة تميز خدمات سحابية — سدايا', 'واحدة من 8+ حالات توظيف داخل سدايا', 'شهادتا ServiceNow: CAD + CSA'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/hind-alhijailan/' },
    ],
  },
  {
    rank: 20, id: 'abdulrahman-alqannas',
    name: 'عبدالرحمن القناص', nameEn: 'Abdulrahman Alqannas',
    photo: 'assets/abdulrahman-alqannas.jpg',
    role: 'أخصائي تعلم آلة وتحليلات متقدمة',
    org: 'شركة علم', orgLogo: 'assets/elm.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: '2023',
    score: 64, verification: 'ب',
    category: 'employment', categories: ['employment'],
    gender: 'm',
    impact: 'أسرع أثر توظيفي في بيانات الأكاديمية: التحاق بشركة علم في سنة التخرج نفسها.',
    story: 'صاحب أسرع أثر توظيفي في بيانات الأكاديمية: أخصائي تعلم آلة وتحليلات متقدمة في شركة علم منذ سنة تخرجه نفسها (2023) من برنامج ممارس النماذج اللغوية الكبيرة. نشاطه في علوم البيانات مؤكد استقلاليًا عبر دفاتر Kaggle العامة.',
    achievements: ['التحاق بشركة علم في سنة التخرج نفسها', 'نشاط علني موثّق على Kaggle'],
    links: [
      { label: 'Kaggle', url: 'https://www.kaggle.com/abdulrahmanalqannas' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdulrahman-alqannas/' },
    ],
  },
];
