/* =========================================================
   SDAIA Academy — Graduate Success Stories · Data
   المصدر: تقرير قصص نجاح الخريجين حسب سنة التخرج (31 يوليو 2026)
   لتحديث القصص: عدّل هذا الملف فقط — العرض يُبنى تلقائيًا.
   ========================================================= */
'use strict';

const SITE_STATS = [
  { value: 31, label: 'قصة نجاح موثّقة', note: 'مرتبة حسب سنة التخرج' },
  { value: 4,  label: 'دفعات خريجين',    note: '2022 – 2025' },
  { value: 25, label: 'جهة عمل',          note: 'حكومية وخاصة وعالمية' },
];

const YEARS = [
  { id: 2022, label: 'دفعة 2022', desc: 'معسكر T5 لعلوم البيانات وبرنامج «أبطال صيف الذكاء الاصطناعي»' },
  { id: 2023, label: 'دفعة 2023', desc: 'معسكرات تعلم الآلة والنماذج اللغوية الكبيرة وإدارة البيانات وحوكمتها' },
  { id: 2024, label: 'دفعة 2024', desc: 'معسكر T5 ومعسكر معالجة الازدحام المروري وبرامج الذكاء الاصطناعي التوليدي' },
  { id: 2025, label: 'دفعة 2025', desc: 'معسكرا هندسة البيانات وServiceNow والتدريب الاحترافي بالذكاء الاصطناعي التوليدي مع NVIDIA' },
];

const CATEGORIES = [
  { id: 'all',        label: 'الكل' },
  { id: 'employment', label: 'التوظيف والتقدم المهني' },
  { id: 'leadership', label: 'القيادة والمواقع الرفيعة' },
  { id: 'research',   label: 'البحث والنشر العلمي' },
  { id: 'opensource', label: 'المصادر المفتوحة' },
  { id: 'awards',     label: 'الجوائز والزمالات' },
  { id: 'startup',    label: 'ريادة الأعمال' },
];

const STORIES = [

  /* ============================ دفعة 2022 ============================ */
  {
    id: 'maram-alfaifi', year: 2022,
    name: 'مرام الفيفي', nameEn: 'Maram Alfaifi',
    photo: 'https://github.com/marama09.png',
    role: 'مهندسة برمجيات — Engineer II ثم مواقع أعلى',
    org: 'شركة TAM للتطوير', orgLogo: 'assets/tam.png',
    program: 'معسكر T5 لعلوم البيانات',
    period: 'نوفمبر 2021 – فبراير 2022',
    category: 'employment', categories: ['employment'],
    impact: 'من المشروع النهائي في المعسكر إلى وظيفة Engineer II في TAM خلال نحو شهرين — أقوى حالة توظيف موثّقة علنيًا في دفعة 2022.',
    story: 'أتمّت مرام معسكر T5 لعلوم البيانات بمشروعها النهائي «Eyes Disease» لتشخيص أمراض العيون، الموثّق علنيًا بتواريخ حتى 10 فبراير 2022، والتحقت بشركة TAM للتطوير بوظيفة Engineer II اعتبارًا من أبريل 2022 — أي خلال نحو شهرين فقط من إتمام البرنامج وبلا دور وسيط. ثم تدرّجت داخل الشركة إلى أدوار هندسية أعلى. حاصلة على بكالوريوس علوم الحاسب من جامعة الأمير سطام بن عبدالعزيز (2020).',
    achievements: ['توظيف موثّق بالتواريخ خلال ~شهرين من التخرج', 'المشروع النهائي «Eyes Disease» منشور علنًا على GitHub', 'تدرّج وظيفي داخل TAM بعد الالتحاق', 'قصة موثّقة بمصادر علنية كاملة'],
    links: [
      { label: 'GitHub', url: 'https://github.com/marama09' },
      { label: 'مشروع Eyes Disease', url: 'https://github.com/marama09/Eyes_Disease' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/maram-alfaifi-b787a01b7' },
    ],
  },
  {
    id: 'maha-altalak', year: 2022,
    name: 'مها الطلق', nameEn: 'Maha Altalak',
    photo: null,
    role: 'رئيسة قطاع نمذجة الذكاء الاصطناعي · مديرة الابتكار بوزارة الصحة',
    org: 'مستشفى صحة الافتراضي — وزارة الصحة', orgLogo: 'assets/moh.png',
    program: 'معسكر T5 لعلوم البيانات + أبطال صيف الذكاء الاصطناعي',
    period: '2021 – 2022',
    category: 'leadership', categories: ['leadership', 'employment'],
    impact: 'من المعسكر إلى التدريس الجامعي في سنة البرنامج نفسها، ثم إلى قيادة نمذجة الذكاء الاصطناعي في أكبر مستشفى افتراضي في العالم.',
    story: 'بعد إتمام برنامجَي الأكاديمية عملت مها محاضِرة في جامعة تبوك في سنة البرنامج نفسها (2022)، ثم مهندسة تعلم آلة في نيوم NEOM (2023–2024)، وتقود منذ 2024 قطاع نمذجة الذكاء الاصطناعي في مستشفى صحة الافتراضي التابع لوزارة الصحة — أكبر مستشفى افتراضي في العالم (موسوعة غينيس) — وتشغل دور مديرة الابتكار بالوزارة منذ 2025. مسارها هو أعلى موقع قيادي موثّق لخريجي معسكرات الأكاديمية في القطاع الصحي الحكومي، وحاصلة على ماجستير الذكاء الاصطناعي من جامعة تبوك.',
    achievements: ['توظيف جامعي في سنة البرنامج نفسها (2022)', 'مهندسة تعلم آلة في نيوم NEOM (2023–2024)', 'رئيسة قطاع نمذجة الذكاء الاصطناعي — مستشفى صحة الافتراضي', 'مديرة الابتكار بوزارة الصحة'],
    links: [
      { label: 'مستودع T5 — GitHub', url: 'https://github.com/Maha-Altalak/SDAIA-T5-Bootcamp' },
      { label: 'عن المستشفى — وزارة الصحة', url: 'https://www.moh.gov.sa/en/ministry/projects/pages/seha-virtual-hospital.aspx' },
    ],
  },

  /* ============================ دفعة 2023 ============================ */
  {
    id: 'abdulrahman-alqannas', year: 2023,
    name: 'عبدالرحمن القناص', nameEn: 'Abdulrahman Alqannas',
    photo: 'assets/abdulrahman-alqannas.jpg',
    role: 'أخصائي تعلم آلة وتحليلات متقدمة',
    org: 'شركة علم', orgLogo: 'assets/elm.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: '2023',
    category: 'employment', categories: ['employment'],
    impact: 'أسرع أثر توظيفي في بيانات الأكاديمية: التحاق بشركة علم في سنة التخرج نفسها.',
    story: 'صاحب أسرع أثر توظيفي في بيانات الأكاديمية: أخصائي تعلم آلة وتحليلات متقدمة في شركة علم منذ سنة تخرجه نفسها (2023) من برنامج ممارس النماذج اللغوية الكبيرة. نشاطه في علوم البيانات مؤكد استقلاليًا عبر دفاتر Kaggle العامة، وحاصل على بكالوريوس نظم المعلومات الإدارية من جامعة الإمام محمد بن سعود.',
    achievements: ['التحاق بشركة علم في سنة التخرج نفسها', 'نشاط علني موثّق على Kaggle'],
    links: [
      { label: 'Kaggle', url: 'https://www.kaggle.com/abdulrahmanalqannas' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdulrahman-alqannas/' },
    ],
  },
  {
    id: 'rayan-dahlawi', year: 2023,
    name: 'ريان دحلاوي', nameEn: 'Rayan Dahlawi',
    photo: 'assets/rayan-dahlawi.jpg',
    role: 'أخصائي علوم بيانات (AI/BI)',
    org: 'عبداللطيف جميل المتحدة للتمويل', orgLogo: 'assets/aljuf.png',
    program: 'معسكر النماذج اللغوية الكبيرة + دورات NVIDIA',
    period: 'ديسمبر 2023 – يوليو 2026',
    category: 'employment', categories: ['employment', 'awards'],
    impact: 'توظيف مؤكد من مصدرين مستقلين، مع خمس دورات NVIDIA معتمدة بعد التخرج.',
    story: 'أخصائي علوم بيانات (AI/BI) في عبداللطيف جميل المتحدة للتمويل (ALJUF). انتسابه ونتيجته مؤكدان من مصدرين مستقلين: الملف الرسمي للمجتازين ومنشوره الذاتي الموسوم على LinkedIn. حاز شهادة LLMs Practitioner (ديسمبر 2023) وخمس دورات NVIDIA معتمدة (يوليو 2026) — نموذج للتعلم المستمر بعد التوظيف.',
    achievements: ['أخصائي علوم بيانات AI/BI في ALJUF', 'شهادة LLMs Practitioner', '5 دورات NVIDIA معتمدة', 'توثيق من مصدرين مستقلين'],
    links: [
      { label: 'منشور المعسكر — LinkedIn', url: 'https://www.linkedin.com/posts/rayan-dahlawi_llmbootcamp-ai-sdaia-activity-7139361304338710528-fzmC' },
    ],
  },
  {
    id: 'weam-abbas', year: 2023,
    name: 'وئام عباس', nameEn: 'Weam Abbas',
    photo: 'assets/weam-abbas.jpg',
    role: 'مهندسة ذكاء اصطناعي (بعد ترقية موثّقة)',
    org: 'أمانة منطقة عسير', orgLogo: 'assets/aseer-municipality.png',
    program: 'معسكر تعلم الآلة + معسكر النماذج اللغوية',
    period: 'أكتوبر – ديسمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'توظيف بعد التخرج ثم ترقية موثّقة بالتسلسل: محللة بيانات (2024) فمهندسة ذكاء اصطناعي (2025).',
    story: 'من أوضح حالات التدرج الوظيفي توثيقًا: التحقت وئام بأمانة عسير محللة بيانات في 2024 بعد اجتيازها معسكرَي تعلم الآلة (أكتوبر 2023) والنماذج اللغوية الكبيرة (ديسمبر 2023)، ثم رُقّيت إلى مهندسة ذكاء اصطناعي في 2025 — ترقية موثّقة بثلاثة مصادر (الملف الرسمي 2023 + بطاقة تعريفية 2026 + ملف مهني).',
    achievements: ['توظيف بعد التخرج: محللة بيانات — أمانة عسير (2024)', 'ترقية موثّقة إلى مهندسة ذكاء اصطناعي (2025)', 'معسكران مجتازان في 2023'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/weam-abbas2/' },
    ],
  },
  {
    id: 'asma-alzahrani', year: 2023,
    name: 'أسماء الزهراني', nameEn: 'Asma Alzahrani',
    photo: null,
    role: 'من التدريب التعاوني إلى وظيفة في سدايا',
    org: 'سدايا', orgLogo: 'assets/sdaia.svg',
    program: 'معسكر النماذج اللغوية الكبيرة + معسكر ثلاثة أشهر',
    period: '2023 – 2024',
    category: 'employment', categories: ['employment', 'research'],
    impact: '«بـ2023 التدريب التعاوني في سدايا، وفي 2024 صرت موظفة فيها» — الدائرة تكتمل بمنشورها العلني.',
    story: 'بدأت أسماء متدربة تعاونية في سدايا عام 2023 بالتوازي مع برامج الأكاديمية، ثم انضمت موظفة في سدايا عام 2024 — كما وثّقت بنفسها في منشورها العلني. وواصلت التطور بحثيًا بورقة علمية في مؤتمر ScholarCon 2025 حول ضبط خوارزمية XGBoost بالتطور التفاضلي لكشف الاحتيال المالي.',
    achievements: ['تدريب تعاوني في سدايا (2023)', 'موظفة في سدايا (2024)', 'ورقة علمية في ScholarCon 2025'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/asma-alzahrani-/' },
    ],
  },
  {
    id: 'faisal-alhumayzi', year: 2023,
    name: 'فيصل الهميزي', nameEn: 'Faisal Alhumayzi',
    photo: 'assets/faisal-alhumayzi.jpg',
    role: 'أخصائي أول ذكاء اصطناعي وعلوم بيانات',
    org: 'مصرف الراجحي', orgLogo: 'assets/alrajhi.webp',
    program: 'ممارس النماذج اللغوية الكبيرة + شهادة مصغرة في علم البيانات',
    period: 'نوفمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'من برامج الأكاديمية إلى فريق الذكاء الاصطناعي وعلوم البيانات في أكبر مصرف إسلامي في العالم.',
    story: 'يعمل فيصل أخصائيًا أول للذكاء الاصطناعي وعلوم البيانات في مصرف الراجحي — الانتساب مؤكد علنيًا عبر سجلات مفهرسة بنطاق بريد المصرف — بعد اجتيازه برنامج ممارس النماذج اللغوية الكبيرة (نوفمبر 2023) وشهادة مصغرة في علم البيانات من الأكاديمية.',
    achievements: ['أخصائي أول ذكاء اصطناعي وعلوم بيانات — مصرف الراجحي', 'ممارس النماذج اللغوية الكبيرة (2023)', 'شهادة مصغرة في علم البيانات'],
    links: [],
  },
  {
    id: 'saad-algarny', year: 2023,
    name: 'سعد القرني', nameEn: 'Saad Algarny',
    photo: 'assets/saad-algarny.jpg',
    role: 'مهندس برمجيات مشارك (Associate Software Engineer)',
    org: 'SAMI للإلكترونيات المتقدمة', orgLogo: 'assets/sami.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: 'نوفمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'التحاق بمنظومة الصناعات الوطنية المتقدمة (SAMI) بدور هندسي مبكر بعد برنامج الأكاديمية.',
    story: 'يعمل سعد مهندس برمجيات مشاركًا في شركة SAMI للإلكترونيات المتقدمة — الانتساب مؤكد بمقتطف ملفه المهني العام — بعد اجتيازه برنامج ممارس النماذج اللغوية الكبيرة (نوفمبر 2023)، وقد سبق له العمل محلل أعمال في بيور الرقمية. لقب «مشارك» (Associate) متسق مع توظيف مبكر بعد التخرج.',
    achievements: ['مهندس برمجيات مشارك — SAMI للإلكترونيات المتقدمة', 'ممارس النماذج اللغوية الكبيرة (2023)'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/saadalgarny/' },
    ],
  },
  {
    id: 'abrar-ghandurah', year: 2023,
    name: 'أبرار غندورة', nameEn: 'Abrar Ghandurah',
    photo: null,
    role: 'مطوّرة تطبيقات',
    org: 'IBM', orgLogo: 'assets/ibm.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: 'ديسمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'من برنامج ممارس النماذج اللغوية الكبيرة إلى تطوير التطبيقات في شركة تقنية عالمية عريقة.',
    story: 'تعمل أبرار مطوّرة تطبيقات في شركة IBM — الانتساب مؤكد علنيًا عبر سجلات مفهرسة بنطاق بريد الشركة — بعد اجتيازها برنامج ممارس النماذج اللغوية الكبيرة (ديسمبر 2023). قصتها ضمن نمط متكرر لوصول خريجي الأكاديمية إلى شركات التقنية العالمية.',
    achievements: ['مطوّرة تطبيقات في IBM', 'ممارس النماذج اللغوية الكبيرة (2023)'],
    links: [],
  },
  {
    id: 'danah-almudaifer', year: 2023,
    name: 'دانة المديفر', nameEn: 'Danah Almudaifer',
    photo: null,
    role: 'مهندسة ذكاء اصطناعي',
    org: 'سدايا', orgLogo: 'assets/sdaia.svg',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: 'ديسمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'إحدى أكثر من ثماني حالات موثّقة لخريجين وظّفتهم سدايا نفسها مهندسي ذكاء اصطناعي.',
    story: 'تعمل دانة مهندسة ذكاء اصطناعي في سدايا — الانتساب مؤكد بمقتطف ملفها المهني العام — بعد اجتيازها برنامج ممارس النماذج اللغوية الكبيرة (ديسمبر 2023). وهي إحدى أكثر من ثماني حالات توظيف موثّقة لخريجي الأكاديمية داخل سدايا نفسها: الهيئة التي درّبتهم وثقت بكفاءتهم فوظّفتهم.',
    achievements: ['مهندسة ذكاء اصطناعي — سدايا', 'إحدى 8+ حالات توظيف خريجين داخل سدايا', 'ممارس النماذج اللغوية الكبيرة (2023)'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/danah-adel-almudaifer/' },
    ],
  },
  {
    id: 'abdullah-alowayyid', year: 2023,
    name: 'عبدالله العويد', nameEn: 'Abdullah Alowayyid',
    photo: 'assets/abdullah-alowayyid.jpg',
    role: 'مهندس — مركز عمليات الشبكات',
    org: 'شركة سايت SITE', orgLogo: 'assets/site-co.png',
    program: 'معسكرا إدارة البيانات وتعلم الآلة + ممارس تعلم الآلة',
    period: '2023 – 2025',
    category: 'employment', categories: ['employment'],
    impact: 'ثلاثة برامج مجتازة في سنة واحدة، وأول توظيف بعد تخرجه الجامعي وبرامج الأكاديمية معًا.',
    story: 'مهندس بمركز عمليات الشبكات في شركة سايت SITE، بعد اجتيازه معسكرَي إدارة البيانات وتعلم الآلة وبرنامج ممارس تعلم الآلة (2023) في السنة نفسها التي نال فيها بكالوريوس تقنية المعلومات من جامعة القصيم — أي أن وظيفته هي أول توظيف بعد تخرجه الجامعي وبرامج الأكاديمية معًا. توثيقه من الأعلى في القاعدة بفضل التطابق المستقل بين بيانات الأكاديمية والمقتطف العام لملفه المهني.',
    achievements: ['مهندس بمركز عمليات الشبكات — SITE', 'ثلاثة برامج مجتازة في 2023', 'أول توظيف بعد التخرج الجامعي وبرامج الأكاديمية'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdullah-alowayid/' },
    ],
  },
  {
    id: 'abdulrahman-alhaji', year: 2023,
    name: 'عبدالرحمن الحاجي', nameEn: 'Abdulrahman Alhaji',
    photo: 'assets/abdulrahman-alhaji.jpg',
    role: 'محلل أول حوكمة بيانات',
    org: 'stc', orgLogo: 'assets/stc.png',
    program: 'معسكر حوكمة البيانات',
    period: 'ديسمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'من معسكر حوكمة البيانات إلى حوكمة البيانات في كبرى شركات الاتصالات السعودية، بشهادتَي CDMP وDCAM.',
    story: 'يعمل عبدالرحمن محللًا أول لحوكمة البيانات في stc — الانتساب مؤكد علنيًا بمصدرين — بعد اجتيازه معسكر حوكمة البيانات (~ديسمبر 2023) الذي وثّق إتمامه بمنشور علني يذكر أطر DAMA وNDMO وGDPR. حاصل على شهادتَي الاعتماد المهني CDMP وDCAM في إدارة وحوكمة البيانات.',
    achievements: ['محلل أول حوكمة بيانات — stc', 'شهادتا CDMP وDCAM المهنيتان', 'معسكر حوكمة البيانات (2023)'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/abdulrahman-alhaji/' },
    ],
  },
  {
    id: 'maha-thafar', year: 2023,
    name: 'د. مها ظفر', nameEn: 'Dr. Maha Thafar',
    photo: null,
    role: 'أستاذة مساعدة — قسم علوم الحاسب',
    org: 'جامعة الطائف', orgLogo: 'assets/taif-university.png',
    program: 'ممارس النماذج اللغوية الكبيرة',
    period: 'ديسمبر 2023',
    category: 'research', categories: ['research'],
    impact: 'أستاذة مساعدة وباحثة منشورة في Scientific Reports تختار برامج الأكاديمية لتحديث مهاراتها في النماذج اللغوية.',
    story: 'حاصلة على الدكتوراه من كاوست (مختبر CBRC للمعلوماتية الحيوية)، وأستاذة مساعدة بقسم علوم الحاسب في جامعة الطائف — مؤكدة على صفحة الجامعة الرسمية. باحثة منشورة بأوراق محكّمة بارزة في التنبؤ بالتفاعلات الدوائية: Affinity2Vec (Scientific Reports، 2022) وDTiGEMS+ وDTi2Vec. قصتها نموذج لالتقاء التأهيل الأكاديمي العميق ببرامج الأكاديمية: باحثة منشورة دوليًا تختار برنامج الأكاديمية تحديثًا لمهاراتها التطبيقية.',
    achievements: ['دكتوراه من كاوست — مختبر CBRC', 'أستاذة مساعدة بجامعة الطائف', 'Affinity2Vec منشورة في Nature Scientific Reports', 'أوراق DTiGEMS+ وDTi2Vec في التنبؤ بالتفاعلات الدوائية'],
    links: [
      { label: 'جامعة الطائف — هيئة التدريس', url: 'https://tu.edu.sa/En/Computer-Science/243/Pages/21459/Faculty-Members' },
      { label: 'Affinity2Vec — Nature', url: 'https://www.nature.com/articles/s41598-022-08787-9' },
      { label: 'GitHub', url: 'https://github.com/MahaThafar' },
    ],
  },
  {
    id: 'mohammed-althunayan', year: 2023,
    name: 'محمد الثنيان', nameEn: 'Mohammed AlThunayan',
    photo: 'assets/mohammed-althunayan.jpg',
    role: 'مهندس برمجيات (Software Engineer I)',
    org: 'J.P. Morgan', orgLogo: 'assets/jpmorgan.png',
    program: 'ممارس تعلم الآلة (Machine Learning Practitioner)',
    period: 'ديسمبر 2023',
    category: 'employment', categories: ['employment'],
    impact: 'أحد أوضح أمثلة الوصول إلى شركة عالمية من الطراز الأول بعد برامج الأكاديمية.',
    story: 'مهندس برمجيات (Software Engineer I) في J.P. Morgan وفق الملف الرسمي — أحد أوضح أمثلة وصول خريجي الأكاديمية إلى شركة عالمية من الطراز الأول. موقعه الشخصي يوثّق تخرجه في هندسة البرمجيات من جامعة الملك فهد للبترول والمعادن (2024) ومشاريعه: TaqaPay وTaskMaster وHealth Guard.',
    achievements: ['Software Engineer I في J.P. Morgan', 'بكالوريوس هندسة برمجيات — كفوبم 2024', 'مشاريع TaqaPay وTaskMaster وHealth Guard'],
    links: [
      { label: 'الموقع الشخصي', url: 'https://malthunayan.com' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/m-althunayan/' },
    ],
  },
  {
    id: 'tala-bakir', year: 2023,
    name: 'تالا بكر', nameEn: 'Tala Bakir',
    photo: 'assets/tala-bakir.jpg',
    role: 'زميلة زمالة قمم · مهندسة برمجيات',
    org: 'زمالة قمم (McKinsey) · شور العالمية للتقنية', orgLogo: 'assets/sure-global.svg',
    program: 'ممارس تعلم الآلة',
    period: 'ديسمبر 2023 – 2025',
    category: 'awards', categories: ['awards', 'employment'],
    impact: 'زميلة دفعة 2025 في زمالة قمم المدعومة من McKinsey — خمسون زميلًا يُنتقون من نحو 18 ألف متقدم.',
    story: 'زميلة زمالة قمم المدعومة من McKinsey & Company — دفعة 2025 المؤكدة على صفحة خريجي الزمالة الرسمية، حيث يُنتقى خمسون زميلًا فقط من نحو 18 ألف متقدم سنويًا، ما يجعلها من أكثر الزمالات القيادية انتقائية في المملكة. اجتازت برنامج ممارس تعلم الآلة (ديسمبر 2023)، وتعمل مهندسة برمجيات في شركة شور العالمية للتقنية.',
    achievements: ['زمالة قمم — دفعة 2025 (بدعم McKinsey)', 'انتقاء من بين ~18,000 متقدم', 'مهندسة برمجيات في شور العالمية'],
    links: [
      { label: 'خريجو قمم', url: 'https://qimam.com/sa/en/alumni/' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/tala-bakir/' },
    ],
  },
  {
    id: 'areej-showail', year: 2023,
    name: 'أريج شويل', nameEn: 'Areej Showail',
    photo: 'assets/areej-showail.jpg',
    role: 'مؤسِّسة مشاركة (Co-Founder)',
    org: 'شركة سِنابس Synapse', orgLogo: 'assets/synapse.png',
    program: 'ممارس تعلم الآلة + معسكر تعلم الآلة',
    period: 'أكتوبر – نوفمبر 2023',
    category: 'startup', categories: ['startup'],
    impact: 'إحدى ثلاث عشرة صلة ريادية موثّقة في القاعدة — وشركتها الناشئة تضم خريجتين للأكاديمية.',
    story: 'مؤسِّسة مشاركة لشركة سِنابس Synapse الناشئة وفق الملف الرسمي للمجتازين — إحدى ثلاث عشرة صلة ريادية موثّقة في القاعدة. تنضم إليها زميلتها أسماء حبادي (نائبة مدير التسويق في Synapse) من الملف نفسه، أي أن الشركة تضم خريجتين للأكاديمية. اجتازت أريج برنامج ممارس تعلم الآلة ومعسكر تعلم الآلة (2023).',
    achievements: ['مؤسِّسة مشاركة لشركة سِنابس', 'الشركة تضم خريجتين للأكاديمية', 'إحدى 13 صلة ريادية موثّقة'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/areej-showail/' },
    ],
  },

  /* ============================ دفعة 2024 ============================ */
  {
    id: 'khalid-alduwaysan', year: 2024,
    name: 'خالد الدويسان', nameEn: 'Khalid Alduwaysan',
    photo: 'assets/khalid-alduwaysan.jpg',
    role: 'مطوّر ذكاء اصطناعي ثم مهندس بيانات في جهة حكومية',
    org: 'أكاديمية الملك سلمان العالمية للغة العربية', orgLogo: null,
    program: 'معسكر T5 لعلوم البيانات والذكاء الاصطناعي',
    period: 'يوليو – أكتوبر 2024',
    category: 'employment', categories: ['employment', 'opensource'],
    impact: 'من التخرج إلى وظيفة «مطوّر ذكاء اصطناعي» خلال نحو ثلاثة أشهر موثّقة بالتواريخ — أقوى حالة في القاعدة كلها.',
    story: 'انتقل خالد من تخرّجه في معسكر T5 (أكتوبر 2024) إلى وظيفة مطوّر ذكاء اصطناعي في أكاديمية الملك سلمان العالمية للغة العربية اعتبارًا من يناير 2025 — أي خلال نحو ثلاثة أشهر فقط، موثقًا بالتواريخ على موقعه الشخصي. بنى نظام «رقيم» لتصحيح النص العربي (OCR + نماذج لغوية)، وشارك في مشروع التخرج RASYD لرصد مخالفات دراجات التوصيل المنشور تطبيقًا حيًّا، ثم واصل التعلم في معسكر هندسة البرمجيات بالأكاديمية السعودية الرقمية، ويعمل حاليًا مهندس بيانات في جهة حكومية.',
    achievements: ['توظيف موثّق بالتواريخ خلال ~3 أشهر من التخرج', 'نظام «رقيم» لتصحيح النص العربي (OCR + نماذج لغوية)', 'عضو فريق مشروع RASYD المنشور تطبيقًا حيًّا', 'مسار تعلم متواصل: معسكر هندسة برمجيات 2025'],
    links: [
      { label: 'الموقع الشخصي', url: 'https://duwaysan.github.io/portfolio/' },
      { label: 'GitHub', url: 'https://github.com/Duwaysan' },
      { label: 'مستودع RASYD', url: 'https://github.com/NasserAlsaqer/Detect-Violated-Motorbikes-Delivery-RASYD' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/kduwaysan/' },
    ],
  },
  {
    id: 'abdulaziz-althumairy', year: 2024,
    name: 'عبدالعزيز التميري', nameEn: 'Abdulaziz Al-Thumairy',
    photo: 'assets/abdulaziz-althumairy.jpg',
    role: 'برنامج تطوير الخريجين · محلل أداء الاستثمارات',
    org: 'صندوق الاستثمارات العامة PIF', orgLogo: 'assets/pif.png',
    program: 'التدريب الاحترافي في النماذج اللغوية الكبيرة',
    period: '2024 – 2025',
    category: 'employment', categories: ['employment'],
    impact: 'من التدريب الاحترافي في النماذج اللغوية إلى برنامج تطوير الخريجين في أكبر صناديق الثروة السيادية.',
    story: 'انضم عبدالعزيز إلى صندوق الاستثمارات العامة PIF ضمن برنامج تطوير الخريجين GDP — البرنامج التدويري المخصص لحديثي التخرج — ويعمل محلل أداء الاستثمارات لمنطقة الشرق الأوسط وشمال أفريقيا (2025)، بعد اجتيازه التدريب الاحترافي في النماذج اللغوية الكبيرة (2024). حاصل على بكالوريوس علوم الحاسب من جامعة المجمعة، وشارك في تنظيم فعالية PIF Digital & Technology Leaders Offsite 2026.',
    achievements: ['برنامج تطوير الخريجين GDP في PIF', 'محلل أداء استثمارات — الشرق الأوسط وشمال أفريقيا', 'مشارك في تنظيم PIF Digital & Technology Leaders Offsite 2026'],
    links: [
      { label: 'LinkedIn', url: 'https://sa.linkedin.com/in/abdulaziz-al-thumairy' },
      { label: 'برنامج GDP — PIF', url: 'https://www.pif.gov.sa/en/careers/graduate-development-program/' },
    ],
  },
  {
    id: 'rana-alharsan', year: 2024,
    name: 'رنا الحرصان', nameEn: 'Rana al-Harsan',
    photo: 'assets/rana-alharsan.jpg',
    role: 'مشروع «رَكَّن» — ضمن أفضل المشاريع من بين 50',
    org: 'فضاء أجا لتقنية المعلومات', orgLogo: 'assets/aja-space.png',
    program: 'معسكر معالجة الازدحام المروري (360 ساعة) + معسكر T5',
    period: 'يوليو – أكتوبر 2024',
    category: 'awards', categories: ['awards', 'employment'],
    impact: 'ضمن دفعة الـ194 التي خرّجتها سدايا رسميًا بتوثيق واس، ومشروعها «رَكَّن» عُرض في حفل التخرج ضمن الأفضل.',
    story: 'ضمن دفعة الـ194 التي خرّجتها سدايا رسميًا في 31 أكتوبر 2024 بتوثيق وكالة الأنباء السعودية، بعد معسكر تقنيات معالجة الازدحام المروري بالبيانات والذكاء الاصطناعي (360 ساعة). اختير مشروعها «رَكَّن» ضمن أفضل المشاريع من بين 50 مشروعًا وعُرض في حفل التخرج، وتعمل لدى فضاء أجا لتقنية المعلومات.',
    achievements: ['مشروع «رَكَّن» ضمن أفضل المشاريع من 50', 'تخريج رسمي موثّق بخبر واس', 'معسكر 360 ساعة في معالجة الازدحام المروري'],
    links: [
      { label: 'خبر التخريج — واس', url: 'https://www.spa.gov.sa/N2199008' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/rana-al-harsan-1792b1257/' },
    ],
  },
  {
    id: 'aljawharah-bintamran', year: 2024,
    name: 'الجوهرة بن طمران', nameEn: 'Aljawharah Bin Tamran',
    photo: 'assets/aljawharah-bintamran.jpg',
    role: 'مهندسة ذكاء اصطناعي أولى (Senior AI Engineer)',
    org: 'HUMAIN — شركة الذكاء الاصطناعي الوطنية', orgLogo: 'assets/humain.png',
    program: 'برامج NVIDIA والذكاء الاصطناعي التوليدي',
    period: '2024',
    category: 'leadership', categories: ['leadership', 'employment', 'research'],
    impact: 'أعلى موقع موثّق لخريجة برامج الأكاديمية داخل الشركة الوطنية الرائدة للذكاء الاصطناعي المملوكة لصندوق الاستثمارات العامة.',
    story: 'تعمل الجوهرة مهندسة ذكاء اصطناعي أولى في HUMAIN — شركة الذكاء الاصطناعي الوطنية المملوكة لصندوق الاستثمارات العامة، المؤسسة في مايو 2025 برئاسة ولي العهد. حازت شهادتَي NVIDIA-Certified Associate في Generative AI LLMs وMultimodal (2024)، وشاركت بانتساب HUMAIN في الورقة العلمية «Octopus: Towards Building the Arabic Speech LLM Suite» المنشورة في ArabicNLP 2025. قصتها تجسّد وصول خريجي الأكاديمية إلى قلب المنظومة التي أُنشئت الأكاديمية لتغذيتها.',
    achievements: ['Senior AI Engineer في HUMAIN', 'شهادتا NVIDIA-Certified Associate: Generative AI LLMs وMultimodal', 'مشاركة في ورقة Octopus — ArabicNLP 2025', 'شركة وطنية مملوكة لصندوق الاستثمارات العامة'],
    links: [
      { label: 'HUMAIN — PIF', url: 'https://www.pif.gov.sa/en/our-investments/our-portfolio/humain/' },
      { label: 'ورقة Octopus — ACL', url: 'https://aclanthology.org/2025.arabicnlp-main.35.pdf' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/aljawharah-bin-tamran-1121461a7/' },
    ],
  },
  {
    id: 'fares-altoukhi', year: 2024,
    name: 'فارس الطوخي', nameEn: 'Fares Altoukhi',
    photo: 'assets/fares-altoukhi.jpg',
    role: 'نماذج عربية مفتوحة على Hugging Face',
    org: 'مساهم مفتوح المصدر — فريق RASYD', orgLogo: null,
    program: 'معسكر T5 — فريق RASYD',
    period: 'أكتوبر 2024',
    category: 'opensource', categories: ['opensource'],
    impact: 'أغنى بصمة مفتوحة المصدر في العيّنة: نماذج عربية مضبوطة منشورة بخدمة REST حية على السحابة.',
    story: 'صاحب أغنى بصمة مفتوحة المصدر في العيّنة: نماذج مضبوطة منشورة على Hugging Face باسمه — Finetuned MarBERT لتحليل المشاعر العربية وArsarcasm لكشف السخرية وSpace لمشروع T5 (أكتوبر 2024) — وخدمة REST على Google Cloud Run (SVM بدقة 89%، وMARBERTv2 بمعامل F1=0.83). إسهامه يسد فجوة عالمية معروفة في موارد اللغة العربية المفتوحة — أثر يتجاوز صاحبه إلى كل من يستخدم نماذجه.',
    achievements: ['نماذج MarBERT وArsarcasm منشورة على Hugging Face', 'خدمة REST حية على Google Cloud Run', 'دقة 89% (SVM) وF1=0.83 (MARBERTv2)', 'إسهام في موارد اللغة العربية المفتوحة'],
    links: [
      { label: 'Hugging Face', url: 'https://huggingface.co/TheKnight115' },
      { label: 'مستودع التحليل العاطفي', url: 'https://github.com/TheKnight909/Emotional-analysis' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/fares-altoukhi/' },
    ],
  },
  {
    id: 'mohammed-almalki', year: 2024,
    name: 'محمد المالكي وفريق ADEL', nameEn: 'Mohammed Almalki & ADEL Team',
    photo: 'assets/mohammed-almalki.jpg',
    role: 'نظام ADEL للإشارات المرورية الذكية',
    org: 'فريق ADEL — معسكر T5', orgLogo: null,
    program: 'معسكر T5 — مشروع التخرج ADEL',
    period: 'أكتوبر 2024',
    category: 'opensource', categories: ['opensource'],
    impact: 'أعلى مشاريع التخرج تقييمًا في سجل المشروع (88/100) — منشور تطبيقًا تفاعليًا على Hugging Face Spaces.',
    story: 'قاد محمد المالكي فريق مشروع ADEL (مع محمد الرويس وخالد الغامدي ووليد الإخوان) — أعلى مشاريع التخرج تقييمًا في سجل المشروع (88/100): نظام إشارات مرورية ذكية بالرؤية الحاسوبية يجمع YOLOv8 وDeepSort وPaddleOCR بدقة كشف مركبات 92% ومحاكاة SUMO، منشور تطبيقًا تفاعليًا على Hugging Face Spaces مع عرض على YouTube.',
    achievements: ['أعلى تقييم لمشاريع التخرج: 88/100', 'YOLOv8 + DeepSort + PaddleOCR — دقة 92%', 'محاكاة SUMO وتطبيق تفاعلي منشور'],
    links: [
      { label: 'مستودع ADEL', url: 'https://github.com/iwm10/ADEL-System' },
      { label: 'التطبيق — HF Spaces', url: 'https://huggingface.co/spaces/M12ths/ADEL_app' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/mohammd-almalkii/' },
    ],
  },

  /* ============================ دفعة 2025 ============================ */
  {
    id: 'rana-alshehri', year: 2025,
    name: 'رنا الشهري', nameEn: 'Rana Alshehri',
    photo: null,
    role: 'مطوّرة ذكاء اصطناعي',
    org: 'مدينة الملك عبدالعزيز للعلوم والتقنية KACST', orgLogo: 'assets/kacst.webp',
    program: 'التدريب الاحترافي بالذكاء الاصطناعي التوليدي والنماذج اللغوية (NVIDIA)',
    period: '2025',
    category: 'employment', categories: ['employment'],
    impact: 'توظيف في KACST في سنة تخرجها الجامعي نفسها — أقوى حالة موثّقة علنيًا في دفعة 2025.',
    story: 'التحقت رنا بمدينة الملك عبدالعزيز للعلوم والتقنية KACST مطوّرةً للذكاء الاصطناعي في 2025 — سنة تخرجها نفسها في بكالوريوس الذكاء الاصطناعي من جامعة الإمام عبدالرحمن بن فيصل — بعد التدريب الاحترافي بالذكاء الاصطناعي التوليدي والنماذج اللغوية المرتبط بشهادات NVIDIA عبر الأكاديمية. وتواصل التعلم في 2026 متدربةً في برنامج Agentic AI بالأكاديمية السعودية الرقمية.',
    achievements: ['مطوّرة ذكاء اصطناعي — KACST في سنة التخرج نفسها', 'بكالوريوس ذكاء اصطناعي — جامعة الإمام عبدالرحمن بن فيصل (2025)', 'مسار تعلم متواصل: Agentic AI (2026)'],
    links: [],
  },
  {
    id: 'shahad-alhajri', year: 2025,
    name: 'شهد الحجري', nameEn: 'Shahad Alhajri',
    photo: 'assets/shahad-alhajri.jpg',
    role: 'مسؤولة ذكاء اصطناعي (AI DEDP Officer)',
    org: 'شركة الدرعية', orgLogo: 'assets/diriyah.png',
    program: 'شهادة NVIDIA Certified Associate: Generative AI & LLMs',
    period: '2025',
    category: 'employment', categories: ['employment'],
    impact: 'من التدريب التعاوني في «علم» إلى وظيفة دائمة في شركة الدرعية خلال سنة التخرج نفسها.',
    story: 'مسار موثّق بالتواريخ في سنة واحدة: تدريب تعاوني في علوم البيانات لدى شركة علم (يناير – مايو 2025) — مؤكد علنيًا — ثم وظيفة دائمة مسؤولةً للذكاء الاصطناعي في شركة الدرعية منذ نوفمبر 2025، في سنة تخرجها الجامعي في علوم الذكاء الاصطناعي نفسها. وأتمّت شهادة NVIDIA Certified Associate في الذكاء الاصطناعي التوليدي والنماذج اللغوية (ديسمبر 2025).',
    achievements: ['وظيفة دائمة في سنة التخرج نفسها — شركة الدرعية', 'تدريب تعاوني موثّق في شركة علم', 'شهادة NVIDIA Certified Associate: Generative AI & LLMs'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/shahad-alhajri/' },
    ],
  },
  {
    id: 'jehad-aljazi', year: 2025,
    name: 'جهاد الجازي', nameEn: 'Jehad Aljazi',
    photo: null,
    role: 'مهندس بيانات',
    org: 'المؤسسة العامة للتأمينات الاجتماعية GOSI', orgLogo: 'assets/gosi.png',
    program: 'معسكر هندسة البيانات (+5 شهادات Microsoft)',
    period: '2025',
    category: 'employment', categories: ['employment'],
    impact: 'بكالوريوس 2024 ← معسكر هندسة البيانات ← مهندس بيانات في GOSI خلال 2025 — نمط «معسكر ← وظيفة» مكتمل.',
    story: 'نال جهاد بكالوريوس علوم الحاسب من جامعة أم القرى (2024)، ثم اجتاز معسكر هندسة البيانات بالأكاديمية (بشراكة Microsoft) نائلًا خمس شهادات Microsoft احترافية خلاله، والتحق في السنة نفسها (2025) بالمؤسسة العامة للتأمينات الاجتماعية GOSI مهندسًا للبيانات — نموذج مكتمل لنمط «معسكر ← وظيفة متخصصة خلال أشهر».',
    achievements: ['مهندس بيانات — GOSI في سنة المعسكر نفسها', '5 شهادات Microsoft احترافية', 'بكالوريوس علوم حاسب — جامعة أم القرى (2024)'],
    links: [],
  },
  {
    id: 'amal-almubarak', year: 2025,
    name: 'أمل المبارك', nameEn: 'Amal Almubarak',
    photo: null,
    role: 'أخصائية ذكاء اصطناعي',
    org: 'المؤسسة العامة للتأمينات الاجتماعية GOSI', orgLogo: 'assets/gosi.png',
    program: 'معسكر هندسة البيانات (+5 شهادات Microsoft)',
    period: '2025',
    category: 'employment', categories: ['employment'],
    impact: 'من بكالوريوس جامعة الملك سعود إلى أخصائية ذكاء اصطناعي في GOSI خلال سنة التخرج نفسها.',
    story: 'نالت أمل بكالوريوس علوم الحاسب من جامعة الملك سعود (2024)، ثم اجتازت معسكر هندسة البيانات بالأكاديمية (بشراكة Microsoft) نائلةً خمس شهادات Microsoft احترافية خلاله، والتحقت في 2025 بالمؤسسة العامة للتأمينات الاجتماعية GOSI أخصائيةً للذكاء الاصطناعي — ثاني خريجي المعسكر التحاقًا بالمؤسسة في العام نفسه.',
    achievements: ['أخصائية ذكاء اصطناعي — GOSI', '5 شهادات Microsoft احترافية', 'بكالوريوس علوم حاسب — جامعة الملك سعود (2024)'],
    links: [],
  },
  {
    id: 'hussein-mohsen', year: 2025,
    name: 'حسين محسن', nameEn: 'Hussein Mohsen',
    photo: 'assets/hussein-mohsen.jpg',
    role: 'مساعد تدريس ذكاء اصطناعي',
    org: 'أكاديمية كاوست', orgLogo: 'assets/kaust-academy.png',
    program: 'معسكر هندسة البيانات — 5 شهادات Microsoft',
    period: '2025',
    category: 'research', categories: ['research', 'employment'],
    impact: 'من بكالوريوس الذكاء الاصطناعي إلى مسار أكاديمي بحثي في مؤسسة نخبوية خلال سنة واحدة.',
    story: 'مساعد تدريس ذكاء اصطناعي في أكاديمية كاوست (2025) — تحوّل من بكالوريوس الذكاء الاصطناعي بجامعة الإمام عبدالرحمن (2024) إلى مسار أكاديمي بحثي في مؤسسة نخبوية خلال سنة واحدة، بعد اجتيازه معسكر هندسة البيانات ونيله خمس شهادات احترافية من Microsoft خلال المعسكر.',
    achievements: ['مساعد تدريس ذكاء اصطناعي — أكاديمية كاوست', '5 شهادات Microsoft احترافية خلال المعسكر', 'انتقال إلى المسار البحثي خلال سنة واحدة'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/hussain-mohsen/' },
    ],
  },
  {
    id: 'majd-alziyadi', year: 2025,
    name: 'مجد الزيادي', nameEn: 'Majd Alziyadi',
    photo: null,
    role: 'مطوّر تطبيقات',
    org: 'IBM', orgLogo: 'assets/ibm.png',
    program: 'معسكر مطوري أنظمة ServiceNow — شهادتا CAD وCSA',
    period: '2025',
    category: 'employment', categories: ['employment', 'awards'],
    impact: 'من معسكر ServiceNow إلى تطوير التطبيقات في IBM بشهادتَي CAD وCSA.',
    story: 'مطوّر تطبيقات في IBM بعد اجتيازه معسكر مطوري أنظمة ServiceNow (2025) ونيله شهادتَي CAD (مطوّر تطبيقات معتمد) وCSA (مدير نظام معتمد)، وحاصل على بكالوريوس علوم الحاسب من جامعة الباحة (2024). قصته ضمن نمط متكرر لخريجي معسكرات 2025 الذين ظهروا في GOSI وIBM وسدايا في العام ذاته — «معسكر ← وظيفة متخصصة خلال أشهر».',
    achievements: ['مطوّر تطبيقات في IBM', 'شهادتا ServiceNow: CAD + CSA', 'توظيف في سنة المعسكر نفسها'],
    links: [],
  },
  {
    id: 'hind-alhijailan', year: 2025,
    name: 'هند الحجيلان', nameEn: 'Hind Alhujailan',
    photo: 'assets/hind-alhijailan.jpg',
    role: 'مسؤولة تميز خدمات الحوسبة السحابية',
    org: 'سدايا', orgLogo: 'assets/sdaia.svg',
    program: 'معسكر مطوري أنظمة ServiceNow — شهادتا CAD وCSA',
    period: '2025',
    category: 'employment', categories: ['employment'],
    impact: 'الدائرة تكتمل: الهيئة التي درّبتها وظّفتها — واحدة من أكثر من ثماني حالات توظيف موثّقة لخريجين داخل سدايا.',
    story: 'مسؤولة تميز خدمات الحوسبة السحابية في سدايا نفسها (2025) — الدائرة تكتمل: الهيئة التي درّبتها وظّفتها. وهي واحدة من أكثر من ثماني حالات توظيف موثّقة لخريجين داخل سدايا. اجتازت معسكر مطوري أنظمة ServiceNow بشهادتَي CAD وCSA، وحاصلة على بكالوريوس تقنية المعلومات من جامعة المجمعة (2024).',
    achievements: ['مسؤولة تميز خدمات سحابية — سدايا', 'واحدة من 8+ حالات توظيف داخل سدايا', 'شهادتا ServiceNow: CAD + CSA'],
    links: [
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/hind-alhijailan/' },
    ],
  },
  {
    id: 'jawaher-alghamdi', year: 2025,
    name: 'د. جواهر الغامدي', nameEn: 'Dr. Jawaher Alghamdi',
    photo: null,
    role: 'عضو هيئة تدريس وباحثة NLP',
    org: 'جامعة الملك خالد', orgLogo: 'assets/kku.png',
    program: 'برنامج NVIDIA المعتمد عبر الأكاديمية',
    period: '2024 – 2025',
    category: 'research', categories: ['research', 'awards'],
    impact: 'سجل نشر بحثي كثيف 2023–2026 في مجلات مصنفة، مع خمس شهادات NVIDIA واعتمادَي NVIDIA-Certified Associate.',
    story: 'عضو هيئة تدريس بجامعة الملك خالد، حاصلة على الدكتوراه من جامعة كوينزلاند، وصاحبة سجل نشر بحثي كثيف (2023–2026) في مجلات مصنفة: Expert Systems with Applications وKnowledge-Based Systems وEngineering Applications of AI في كشف الأخبار الزائفة ومعالجة اللغة، ومشاركة في PAKDD 2025 Doctoral Consortium. أتمّت خمس شهادات دورات في برنامج NVIDIA المعتمد عبر الأكاديمية وشهادتَي NVIDIA-Certified Associate، إلى جانب زمالة مسك وAWS AI/ML Scholar.',
    achievements: ['دكتوراه من جامعة كوينزلاند', 'نشر في Expert Systems with Applications وKnowledge-Based Systems', 'PAKDD 2025 Doctoral Consortium', '5 شهادات NVIDIA + شهادتا NVIDIA-Certified Associate'],
    links: [
      { label: 'DBLP', url: 'https://dblp.org/pid/214/6817.html' },
      { label: 'Google Scholar', url: 'https://scholar.google.com/citations?user=tAfpHygAAAAJ' },
      { label: 'PAKDD 2025', url: 'https://pakdd2025.org/doc/Consortium/Jawaher-Alghamdi-PAKDD25-DC.pdf' },
    ],
  },
  {
    id: 'wadha-almattar', year: 2025,
    name: 'د. وضحة المطر', nameEn: 'Dr. Wadha Almattar',
    photo: 'assets/wadha-almattar.jpg',
    role: 'أستاذة مساعدة ورئيسة قسم هندسة الحاسب',
    org: 'جامعة الإمام عبدالرحمن بن فيصل', orgLogo: 'assets/iau.png',
    program: 'برنامج NVIDIA المعتمد عبر الأكاديمية',
    period: '2024 – 2025',
    category: 'leadership', categories: ['leadership', 'research'],
    impact: 'رئاسة قسم هندسة الحاسب منذ أغسطس 2025، وتحت قيادة القسم أُطلق برنامج بكالوريوس الذكاء الاصطناعي.',
    story: 'أستاذة مساعدة بجامعة الإمام عبدالرحمن بن فيصل (صفحة رسمية مؤكدة)، ورئيسة قسم هندسة الحاسب منذ أغسطس 2025، وتحت قيادة القسم أُطلق برنامج بكالوريوس الذكاء الاصطناعي. خريجة كاوست وكفوبم وباحثة رؤية حاسوبية، أتمّت برنامج NVIDIA المعتمد عبر الأكاديمية وشهادتَي NVIDIA-Certified Associate (فبراير 2025).',
    achievements: ['رئيسة قسم هندسة الحاسب منذ أغسطس 2025', 'إطلاق برنامج بكالوريوس الذكاء الاصطناعي', 'باحثة رؤية حاسوبية — خريجة كاوست وكفوبم', 'شهادتا NVIDIA-Certified Associate'],
    links: [
      { label: 'صفحتها — جامعة الإمام عبدالرحمن', url: 'https://www.iau.edu.sa/en/colleges/college-of-computer-science-and-information-technology/faculty/wadha-muteb-al-mattar' },
      { label: 'Google Scholar', url: 'https://scholar.google.com/citations?user=k_AKQ9UAAAAJ' },
    ],
  },
];
